/**
 * Fundamentals types, constants, formatters, and normalizers.
 * Wire-format types match the backend /api/fundamentals/{symbol} response exactly.
 * @generated by code-generator (Agent #19)
 */

// ---------------------------------------------------------------------------
// Wire-format types (snake_case -- matches backend response)
// ---------------------------------------------------------------------------

/** Trailing-twelve-months fundamentals as returned by the backend. */
export interface FundamentalsTtmRaw {
  readonly revenue: number | null;
  readonly net_income: number | null;
  readonly eps_diluted: number | null;
  readonly gross_margin: number | null;
  readonly operating_margin: number | null;
  readonly net_margin: number | null;
  readonly pe_ratio: number | null;
  readonly market_cap: number | null;
  readonly shares_outstanding: number | null;
  readonly free_cash_flow: number | null;
  readonly debt_to_equity: number | null;
  readonly return_on_equity: number | null;
  readonly dividend_yield: number | null;
}

/** Single quarterly filing as returned by the backend. */
export interface FundamentalsQuarterRaw {
  readonly period: string;
  readonly filing_date: string | null;
  readonly filing_type: string;
  readonly revenue: number | null;
  readonly net_income: number | null;
  readonly eps_diluted: number | null;
  readonly gross_margin: number | null;
  readonly operating_margin: number | null;
  readonly net_margin: number | null;
  readonly revenue_growth_yoy: number | null;
  readonly eps_growth_yoy: number | null;
  readonly free_cash_flow?: number | null;
}

/** Full envelope response from GET /api/fundamentals/{symbol}. */
export interface FundamentalsApiResponse {
  readonly symbol: string;
  readonly company_name: string | null;
  readonly cik: string | null;
  readonly ttm: FundamentalsTtmRaw | null;
  readonly quarterly: FundamentalsQuarterRaw[];
  readonly next_earnings_date: null;
  readonly data_sources: {
    readonly financials: string;
    readonly market_data: string;
  };
  readonly data_timestamp: string;
  readonly note?: string;
}

export interface ShortInterestRaw {
  readonly symbol: string;
  readonly shares_short: number | null;
  readonly short_ratio: number | null;
  readonly percent_of_float: number | null;
  readonly settlement_date: string | null;
}

export interface AnalystRatingsRaw {
  readonly symbol: string;
  readonly buy: number;
  readonly hold: number;
  readonly sell: number;
  readonly consensus: string;
  readonly total_analysts: number;
  readonly price_target_mean: number | null;
  readonly price_target_high: number | null;
  readonly price_target_low: number | null;
}

// ---------------------------------------------------------------------------
// Display types (camelCase -- for React components)
// ---------------------------------------------------------------------------

/** Normalised TTM fundamentals ready for rendering. */
export interface FundamentalsTtm {
  readonly revenue: number | null;
  readonly netIncome: number | null;
  readonly epsDiluted: number | null;
  readonly grossMargin: number | null;
  readonly operatingMargin: number | null;
  readonly netMargin: number | null;
  readonly peRatio: number | null;
  readonly marketCap: number | null;
  readonly sharesOutstanding: number | null;
  readonly freeCashFlow: number | null;
  readonly debtToEquity: number | null;
  readonly returnOnEquity: number | null;
  readonly dividendYield: number | null;
}

/** Normalised quarterly filing ready for rendering. */
export interface FundamentalsQuarter {
  readonly period: string;
  readonly filingDate: string | null;
  readonly filingType: string;
  readonly revenue: number | null;
  readonly netIncome: number | null;
  readonly epsDiluted: number | null;
  readonly grossMargin: number | null;
  readonly operatingMargin: number | null;
  readonly netMargin: number | null;
  readonly revenueGrowthYoy: number | null;
  readonly epsGrowthYoy: number | null;
  readonly freeCashFlow: number | null;
}

/** Normalised fundamentals data ready for rendering. */
export interface FundamentalsData {
  readonly symbol: string;
  readonly companyName: string | null;
  readonly ttm: FundamentalsTtm | null;
  readonly quarterly: FundamentalsQuarter[];
  readonly dataSources: {
    readonly financials: string;
    readonly marketData: string;
  };
  readonly dataTimestamp: string;
}

export interface ShortInterest {
  readonly symbol: string;
  readonly sharesShort: number | null;
  readonly shortRatio: number | null;
  readonly percentOfFloat: number | null;
  readonly settlementDate: string | null;
}

export interface AnalystRatings {
  readonly symbol: string;
  readonly buy: number;
  readonly hold: number;
  readonly sell: number;
  readonly consensus: string;
  readonly totalAnalysts: number;
  readonly priceTargetMean: number | null;
  readonly priceTargetHigh: number | null;
  readonly priceTargetLow: number | null;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Client-side cache TTL for fundamentals data (15 minutes). */
export const FUNDAMENTALS_CACHE_TTL_MS = 900_000;

// ---------------------------------------------------------------------------
// Helpers -- type guards & sanitizers
// ---------------------------------------------------------------------------

/**
 * Type guard: returns true only for finite numeric values.
 *
 * Rejects `null`, `undefined`, `NaN`, `Infinity`, `-Infinity`, booleans,
 * strings, and any other non-number type.
 */
export function isDisplayable(value: unknown): value is number {
  return typeof value === 'number' && Number.isFinite(value);
}

/**
 * Defensively coerce an unknown value to `number | null`.
 *
 * Returns the value as a number when it is a finite, non-boolean number;
 * returns `null` for everything else (including `NaN`, `Infinity`, booleans,
 * strings, objects, `undefined`, and `null`).
 */
function sanitizeNumber(value: unknown): number | null {
  if (typeof value === 'boolean') return null;
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  return null;
}

// ---------------------------------------------------------------------------
// Formatters
// ---------------------------------------------------------------------------

/**
 * Format a currency value with K/M/B/T suffixes.
 *
 * - Returns `'--'` when the value is not displayable.
 * - Handles negative values (prefixes with `-`).
 * - Uses 2 decimal places after the suffix division.
 *
 * @example
 * formatCurrency(1_500_000)   // "$1.50M"
 * formatCurrency(-2_300)      // "-$2.30K"
 * formatCurrency(null)        // "--"
 */
export function formatCurrency(value: number | null): string {
  if (!isDisplayable(value)) return '--';

  const sign = value < 0 ? '-' : '';
  const abs = Math.abs(value);

  if (abs >= 1e12) return `${sign}$${(abs / 1e12).toFixed(2)}T`;
  if (abs >= 1e9) return `${sign}$${(abs / 1e9).toFixed(2)}B`;
  if (abs >= 1e6) return `${sign}$${(abs / 1e6).toFixed(2)}M`;
  if (abs >= 1e3) return `${sign}$${(abs / 1e3).toFixed(2)}K`;

  return `${sign}$${abs.toFixed(2)}`;
}

/**
 * Format a decimal ratio as a percentage string.
 *
 * The backend sends decimals (e.g. `0.45` for 45%), so this function
 * multiplies by 100 before formatting.
 *
 * @example
 * formatPercent(0.4523)  // "45.23%"
 * formatPercent(-0.12)   // "-12.00%"
 * formatPercent(null)    // "--"
 */
export function formatPercent(value: number | null): string {
  if (!isDisplayable(value)) return '--';
  return `${(value * 100).toFixed(2)}%`;
}

/**
 * Format a numeric ratio to 2 decimal places.
 *
 * @example
 * formatRatio(1.456)  // "1.46"
 * formatRatio(null)   // "--"
 */
export function formatRatio(value: number | null): string {
  if (!isDisplayable(value)) return '--';
  return value.toFixed(2);
}

/**
 * Format an earnings-per-share value as a dollar amount.
 *
 * Negative EPS is displayed with a leading minus sign before the dollar sign.
 *
 * @example
 * formatEps(3.42)   // "$3.42"
 * formatEps(-1.05)  // "-$1.05"
 * formatEps(null)   // "--"
 */
export function formatEps(value: number | null): string {
  if (!isDisplayable(value)) return '--';
  const sign = value < 0 ? '-' : '';
  return `${sign}$${Math.abs(value).toFixed(2)}`;
}

// ---------------------------------------------------------------------------
// Normalizers
// ---------------------------------------------------------------------------

/**
 * Normalise a single raw quarterly record from snake_case to camelCase.
 *
 * The optional `free_cash_flow` field is coalesced to `null` when absent.
 */
export function normalizeQuarter(
  raw: FundamentalsQuarterRaw,
): FundamentalsQuarter {
  return {
    period: raw.period,
    filingDate: raw.filing_date,
    filingType: raw.filing_type,
    revenue: sanitizeNumber(raw.revenue),
    netIncome: sanitizeNumber(raw.net_income),
    epsDiluted: sanitizeNumber(raw.eps_diluted),
    grossMargin: sanitizeNumber(raw.gross_margin),
    operatingMargin: sanitizeNumber(raw.operating_margin),
    netMargin: sanitizeNumber(raw.net_margin),
    revenueGrowthYoy: sanitizeNumber(raw.revenue_growth_yoy),
    epsGrowthYoy: sanitizeNumber(raw.eps_growth_yoy),
    freeCashFlow: sanitizeNumber(raw.free_cash_flow ?? null),
  };
}

/**
 * Normalise the full backend response into the display-ready format.
 *
 * - Maps all snake_case fields to camelCase.
 * - Handles `ttm: null` gracefully.
 * - Guards `quarterly` against non-array values.
 * - Sanitizes every numeric field through `sanitizeNumber`.
 */
export function normalizeFundamentals(
  raw: FundamentalsApiResponse,
): FundamentalsData {
  const ttm: FundamentalsTtm | null =
    raw.ttm != null
      ? {
        revenue: sanitizeNumber(raw.ttm.revenue),
        netIncome: sanitizeNumber(raw.ttm.net_income),
        epsDiluted: sanitizeNumber(raw.ttm.eps_diluted),
        grossMargin: sanitizeNumber(raw.ttm.gross_margin),
        operatingMargin: sanitizeNumber(raw.ttm.operating_margin),
        netMargin: sanitizeNumber(raw.ttm.net_margin),
        peRatio: sanitizeNumber(raw.ttm.pe_ratio),
        marketCap: sanitizeNumber(raw.ttm.market_cap),
        sharesOutstanding: sanitizeNumber(raw.ttm.shares_outstanding),
        freeCashFlow: sanitizeNumber(raw.ttm.free_cash_flow),
        debtToEquity: sanitizeNumber(raw.ttm.debt_to_equity),
        returnOnEquity: sanitizeNumber(raw.ttm.return_on_equity),
        dividendYield: sanitizeNumber(raw.ttm.dividend_yield),
      }
      : null;

  const quarterly: FundamentalsQuarter[] = Array.isArray(raw.quarterly)
    ? raw.quarterly.map(normalizeQuarter)
    : [];

  return {
    symbol: raw.symbol,
    companyName: raw.company_name,
    ttm,
    quarterly,
    dataSources: {
      financials: raw.data_sources.financials,
      marketData: raw.data_sources.market_data,
    },
    dataTimestamp: raw.data_timestamp,
  };
}

export function normalizeShortInterest(raw: ShortInterestRaw): ShortInterest {
  return {
    symbol: raw.symbol,
    sharesShort: sanitizeNumber(raw.shares_short),
    shortRatio: sanitizeNumber(raw.short_ratio),
    percentOfFloat: sanitizeNumber(raw.percent_of_float),
    settlementDate: raw.settlement_date,
  };
}

export function normalizeAnalystRatings(raw: AnalystRatingsRaw): AnalystRatings {
  return {
    symbol: raw.symbol,
    buy: sanitizeNumber(raw.buy) || 0,
    hold: sanitizeNumber(raw.hold) || 0,
    sell: sanitizeNumber(raw.sell) || 0,
    consensus: raw.consensus,
    totalAnalysts: sanitizeNumber(raw.total_analysts) || 0,
    priceTargetMean: sanitizeNumber(raw.price_target_mean),
    priceTargetHigh: sanitizeNumber(raw.price_target_high),
    priceTargetLow: sanitizeNumber(raw.price_target_low),
  };
}
