/**
 * Macro calendar types, constants, validation, and normalizers for the
 * MacroCalendar panel and macro-related components.
 *
 * Wire-format types match the backend /api/macro/calendar and
 * /api/macro/reaction/{symbol}/{event_type} responses exactly.
 * Display types use camelCase for React component consumption.
 *
 * @generated by code-generator (Agent #19)
 */

// ---------------------------------------------------------------------------
// Type literal unions
// ---------------------------------------------------------------------------

export type ImportanceLevel = 'high' | 'medium' | 'low';

export type SurpriseDirection = 'above' | 'below' | 'inline';

export type MacroEventType =
  | 'cpi'
  | 'core_cpi'
  | 'ism_manufacturing'
  | 'ism_services'
  | 'nfp'
  | 'unemployment'
  | 'fomc'
  | 'gdp'
  | 'ppi'
  | 'retail_sales'
  | 'housing_starts'
  | 'building_permits'
  | 'consumer_confidence'
  | 'durable_goods'
  | 'fed_funds_rate';

// ---------------------------------------------------------------------------
// Wire-format types (snake_case -- matches backend response)
// ---------------------------------------------------------------------------

/** Single calendar event as returned by GET /api/macro/calendar. */
export interface MacroCalendarEventRaw {
  readonly event_name: string;
  readonly event_type: string | null;
  readonly date: string | null;
  readonly time: string | null;
  readonly country: string;
  readonly expected: number | null;
  readonly previous: number | null;
  readonly actual: number | null;
  readonly unit: string;
  readonly importance: string;
  readonly description: string;
}

/** Envelope response from GET /api/macro/calendar. */
export interface MacroCalendarApiResponse {
  readonly events: MacroCalendarEventRaw[];
  readonly date_range: { readonly from: string; readonly to: string };
  readonly data_source: string;
  readonly data_timestamp: string;
}

/** Single reaction entry as returned by GET /api/macro/reaction/{symbol}/{event_type}. */
export interface MacroReactionRaw {
  readonly event_date: string;
  readonly event_value: number | null;
  readonly expected: number | null;
  readonly surprise: string;
  readonly price_before: number | null;
  readonly price_after_1d: number | null;
  readonly price_after_5d: number | null;
  readonly return_1d_percent: number | null;
  readonly return_5d_percent: number | null;
  readonly volume_ratio: number | null;
}

/** Averages sub-object as returned by GET /api/macro/reaction/{symbol}/{event_type}. */
export interface MacroReactionAveragesRaw {
  readonly avg_return_1d_on_beat: number | null;
  readonly avg_return_1d_on_miss: number | null;
  readonly avg_return_5d_on_beat: number | null;
  readonly avg_return_5d_on_miss: number | null;
  readonly avg_volume_ratio: number | null;
}

/** Envelope response from GET /api/macro/reaction/{symbol}/{event_type}. */
export interface MacroReactionApiResponse {
  readonly symbol: string;
  readonly event_type: string;
  readonly reactions: MacroReactionRaw[];
  readonly averages: MacroReactionAveragesRaw;
  readonly sample_size: number;
  readonly data_sources: string[];
  readonly data_timestamp: string;
}

// ---------------------------------------------------------------------------
// Display types (camelCase -- for React components)
// ---------------------------------------------------------------------------

/** Normalised calendar event ready for rendering. */
export interface MacroCalendarEvent {
  readonly eventName: string;
  readonly eventType: MacroEventType | null;
  readonly date: string;
  readonly time: string;
  readonly country: string;
  readonly expected: number | null;
  readonly previous: number | null;
  readonly actual: number | null;
  readonly unit: string;
  readonly importance: ImportanceLevel;
  readonly description: string;
}

/** Normalised calendar data ready for rendering. */
export interface MacroCalendarData {
  readonly events: MacroCalendarEvent[];
  readonly dateRange: { readonly from: string; readonly to: string };
  readonly dataSource: string;
  readonly dataTimestamp: string;
}

/** Normalised reaction entry ready for rendering. */
export interface MacroReaction {
  readonly eventDate: string;
  readonly eventValue: number | null;
  readonly expected: number | null;
  readonly surprise: SurpriseDirection;
  readonly priceBefore: number | null;
  readonly priceAfter1d: number | null;
  readonly priceAfter5d: number | null;
  readonly return1dPercent: number | null;
  readonly return5dPercent: number | null;
  readonly volumeRatio: number | null;
}

/** Normalised reaction averages ready for rendering. */
export interface MacroReactionAverages {
  readonly avgReturn1dOnBeat: number | null;
  readonly avgReturn1dOnMiss: number | null;
  readonly avgReturn5dOnBeat: number | null;
  readonly avgReturn5dOnMiss: number | null;
  readonly avgVolumeRatio: number | null;
}

/** Normalised reaction data ready for rendering. */
export interface MacroReactionData {
  readonly symbol: string;
  readonly eventType: string;
  readonly reactions: MacroReaction[];
  readonly averages: MacroReactionAverages;
  readonly sampleSize: number;
  readonly dataSources: string[];
  readonly dataTimestamp: string;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Client-side cache TTL for calendar data (5 minutes). */
export const MACRO_CALENDAR_CACHE_TTL_MS = 300_000;

/** Client-side cache TTL for reaction data (15 minutes). */
export const MACRO_REACTION_CACHE_TTL_MS = 900_000;

/** Default number of past days to include in calendar fetch. */
export const MACRO_CALENDAR_PAST_DAYS = 7;

/** Default number of future days to include in calendar fetch. */
export const MACRO_CALENDAR_FUTURE_DAYS = 30;

/** Tailwind color stem mapping for each event type. */
export const EVENT_TYPE_COLORS: Readonly<Record<MacroEventType, string>> = {
  cpi: 'red',
  core_cpi: 'rose',
  ism_manufacturing: 'blue',
  ism_services: 'sky',
  nfp: 'amber',
  unemployment: 'orange',
  fomc: 'purple',
  gdp: 'emerald',
  ppi: 'pink',
  retail_sales: 'teal',
  housing_starts: 'cyan',
  building_permits: 'indigo',
  consumer_confidence: 'yellow',
  durable_goods: 'lime',
  fed_funds_rate: 'violet',
} as const;

/** Human-readable display names for each event type. */
export const EVENT_TYPE_DISPLAY_NAMES: Readonly<Record<MacroEventType, string>> = {
  cpi: 'CPI',
  core_cpi: 'Core CPI',
  ism_manufacturing: 'ISM Mfg',
  ism_services: 'ISM Svc',
  nfp: 'NFP',
  unemployment: 'Unemployment',
  fomc: 'FOMC',
  gdp: 'GDP',
  ppi: 'PPI',
  retail_sales: 'Retail Sales',
  housing_starts: 'Housing Starts',
  building_permits: 'Building Permits',
  consumer_confidence: 'Consumer Conf',
  durable_goods: 'Durable Goods',
  fed_funds_rate: 'Fed Funds',
} as const;

/** Set of valid event type strings for runtime validation. */
export const VALID_EVENT_TYPES: ReadonlySet<string> = new Set<MacroEventType>([
  'cpi',
  'core_cpi',
  'ism_manufacturing',
  'ism_services',
  'nfp',
  'unemployment',
  'fomc',
  'gdp',
  'ppi',
  'retail_sales',
  'housing_starts',
  'building_permits',
  'consumer_confidence',
  'durable_goods',
  'fed_funds_rate',
]);

/** Display configuration for importance badges. */
export interface ImportanceConfig {
  readonly label: string;
  readonly colorClass: string;
}

/** Importance-level to display configuration map. */
export const IMPORTANCE_CONFIG: Readonly<Record<ImportanceLevel, ImportanceConfig>> = {
  high: { label: 'High', colorClass: 'text-accent-red' },
  medium: { label: 'Med', colorClass: 'text-accent-yellow' },
  low: { label: 'Low', colorClass: 'text-text-muted' },
} as const;

// ---------------------------------------------------------------------------
// Validation sets (private)
// ---------------------------------------------------------------------------

const VALID_IMPORTANCE_LEVELS: ReadonlySet<string> = new Set<ImportanceLevel>([
  'high',
  'medium',
  'low',
]);

const VALID_SURPRISE_DIRECTIONS: ReadonlySet<string> = new Set<SurpriseDirection>([
  'above',
  'below',
  'inline',
]);

// ---------------------------------------------------------------------------
// Helpers -- sanitizers (private)
// ---------------------------------------------------------------------------

/**
 * Defensively coerce an unknown value to `number | null`.
 *
 * Returns the value as a number when it is a finite, non-boolean number;
 * returns `null` for everything else (including `NaN`, `Infinity`, booleans,
 * strings, objects, `undefined`, and `null`).
 *
 * IMPORTANT: The boolean check MUST come first because
 * `typeof true === 'boolean'` but `true` would also pass a naive
 * `typeof value === 'number'` check in JavaScript (bool is a subclass of
 * number in some contexts).
 */
function sanitizeNumber(value: unknown): number | null {
  if (typeof value === 'boolean') return null;
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  return null;
}

// ---------------------------------------------------------------------------
// Normalizers -- enum validators (exported)
// ---------------------------------------------------------------------------

/**
 * Normalise a raw importance value to a valid ImportanceLevel.
 *
 * Returns the value as-is when it matches a known level; falls back to
 * `'low'` for unknown, missing, or non-string values.
 */
export function normalizeImportance(raw: unknown): ImportanceLevel {
  if (typeof raw === 'string' && VALID_IMPORTANCE_LEVELS.has(raw)) {
    return raw as ImportanceLevel;
  }
  return 'low';
}

/**
 * Normalise a raw surprise direction to a valid SurpriseDirection.
 *
 * Returns the value as-is when it matches a known direction; falls back to
 * `'inline'` for unknown, missing, or non-string values.
 */
export function normalizeSurprise(raw: unknown): SurpriseDirection {
  if (typeof raw === 'string' && VALID_SURPRISE_DIRECTIONS.has(raw)) {
    return raw as SurpriseDirection;
  }
  return 'inline';
}

// ---------------------------------------------------------------------------
// Normalizers -- composite types (exported)
// ---------------------------------------------------------------------------

/**
 * Normalise a single raw calendar event from snake_case to camelCase.
 *
 * - Importance is validated against known levels.
 * - event_type is validated against known event types (null if unknown).
 * - Numeric fields are sanitized through `sanitizeNumber`.
 */
export function normalizeCalendarEvent(raw: MacroCalendarEventRaw): MacroCalendarEvent {
  const rawEventType = raw.event_type;
  const eventType: MacroEventType | null =
    typeof rawEventType === 'string' && VALID_EVENT_TYPES.has(rawEventType)
      ? (rawEventType as MacroEventType)
      : null;

  return {
    eventName: raw.event_name ?? '',
    eventType,
    date: raw.date ?? '',
    time: raw.time ?? '',
    country: raw.country ?? 'US',
    expected: sanitizeNumber(raw.expected),
    previous: sanitizeNumber(raw.previous),
    actual: sanitizeNumber(raw.actual),
    unit: raw.unit ?? '',
    importance: normalizeImportance(raw.importance),
    description: raw.description ?? '',
  };
}

/**
 * Normalise the full calendar API response into the display-ready format.
 *
 * - Maps all snake_case fields to camelCase.
 * - Validates enum fields against known values.
 * - Guards arrays against non-array values.
 */
export function normalizeCalendar(raw: MacroCalendarApiResponse): MacroCalendarData {
  const events: MacroCalendarEvent[] = Array.isArray(raw.events)
    ? raw.events.map(normalizeCalendarEvent)
    : [];

  const dateRange =
    typeof raw.date_range === 'object' &&
    raw.date_range !== null &&
    !Array.isArray(raw.date_range)
      ? { from: raw.date_range.from ?? '', to: raw.date_range.to ?? '' }
      : { from: '', to: '' };

  return {
    events,
    dateRange,
    dataSource: raw.data_source ?? '',
    dataTimestamp: raw.data_timestamp ?? '',
  };
}

/**
 * Normalise a single raw reaction entry from snake_case to camelCase.
 *
 * - Surprise direction is validated against known values.
 * - All numeric fields are sanitized through `sanitizeNumber`.
 */
export function normalizeReactionEntry(raw: MacroReactionRaw): MacroReaction {
  return {
    eventDate: raw.event_date ?? '',
    eventValue: sanitizeNumber(raw.event_value),
    expected: sanitizeNumber(raw.expected),
    surprise: normalizeSurprise(raw.surprise),
    priceBefore: sanitizeNumber(raw.price_before),
    priceAfter1d: sanitizeNumber(raw.price_after_1d),
    priceAfter5d: sanitizeNumber(raw.price_after_5d),
    return1dPercent: sanitizeNumber(raw.return_1d_percent),
    return5dPercent: sanitizeNumber(raw.return_5d_percent),
    volumeRatio: sanitizeNumber(raw.volume_ratio),
  };
}

/**
 * Normalise the full reaction API response into the display-ready format.
 *
 * - Maps all snake_case fields to camelCase.
 * - Validates enum fields against known values.
 * - Sanitizes all numeric fields.
 * - Guards arrays against non-array values.
 */
export function normalizeReaction(raw: MacroReactionApiResponse): MacroReactionData {
  const reactions: MacroReaction[] = Array.isArray(raw.reactions)
    ? raw.reactions.map(normalizeReactionEntry)
    : [];

  const rawAvg = raw.averages;
  const averages: MacroReactionAverages =
    typeof rawAvg === 'object' && rawAvg !== null && !Array.isArray(rawAvg)
      ? {
          avgReturn1dOnBeat: sanitizeNumber(rawAvg.avg_return_1d_on_beat),
          avgReturn1dOnMiss: sanitizeNumber(rawAvg.avg_return_1d_on_miss),
          avgReturn5dOnBeat: sanitizeNumber(rawAvg.avg_return_5d_on_beat),
          avgReturn5dOnMiss: sanitizeNumber(rawAvg.avg_return_5d_on_miss),
          avgVolumeRatio: sanitizeNumber(rawAvg.avg_volume_ratio),
        }
      : {
          avgReturn1dOnBeat: null,
          avgReturn1dOnMiss: null,
          avgReturn5dOnBeat: null,
          avgReturn5dOnMiss: null,
          avgVolumeRatio: null,
        };

  const sampleSizeRaw = sanitizeNumber(raw.sample_size);
  const sampleSize =
    sampleSizeRaw !== null ? Math.max(0, Math.round(sampleSizeRaw)) : 0;

  return {
    symbol: raw.symbol ?? '',
    eventType: raw.event_type ?? '',
    reactions,
    averages,
    sampleSize,
    dataSources: Array.isArray(raw.data_sources) ? raw.data_sources : [],
    dataTimestamp: raw.data_timestamp ?? '',
  };
}

// ---------------------------------------------------------------------------
// Formatters (exported)
// ---------------------------------------------------------------------------

/**
 * Format a numeric event value with its unit for display.
 *
 * Returns '--' for null values. Uses === null (not falsiness) so that
 * 0 is a valid displayable number.
 */
export function formatEventValue(value: number | null, unit: string): string {
  if (value === null) return '--';

  switch (unit) {
    case 'percent':
      return `${value.toFixed(1)}%`;
    case 'index':
      return value.toFixed(1);
    case 'thousands':
      return `${value.toFixed(0)}K`;
    case 'millions_usd':
      return `$${value.toFixed(0)}M`;
    case 'billions_usd':
      return `$${value.toFixed(1)}B`;
    default:
      return value.toFixed(2);
  }
}

/**
 * Format a surprise indicator for display.
 *
 * Returns a directional indicator with the delta value, or '--' when
 * delta is null.
 */
export function formatSurprise(direction: SurpriseDirection, delta: number | null): string {
  if (delta === null) return '--';

  const absDelta = Math.abs(delta).toFixed(2);
  switch (direction) {
    case 'above':
      return `+${absDelta}`;
    case 'below':
      return `-${absDelta}`;
    case 'inline':
      return '0.00';
  }
}
