/**
 * News feed types and constants for the NewsFeed component.
 * Wire-format types match the backend /api/news/{symbol} response exactly.
 * @generated by code-generator (Agent #19)
 */

// ---------------------------------------------------------------------------
// Wire-format types (snake_case -- matches backend response)
// ---------------------------------------------------------------------------

/** Single article as returned by the backend. */
export interface NewsArticleRaw {
  readonly id: string;
  readonly headline: string | null;
  readonly summary: string;
  readonly source: string | null;
  readonly url: string | null;
  readonly image_url: string | null;
  readonly published_at: string | null;
  readonly category: string | null;
  readonly related_tickers: string[];
  readonly sentiment: SentimentDirection | null;
  readonly sentiment_score: number | null;
}

/** Full envelope response from GET /api/news/{symbol}. */
export interface NewsApiResponse {
  readonly symbol: string;
  readonly articles: NewsArticleRaw[];
  readonly total_count: number;
  readonly limit: number;
  readonly offset: number;
  readonly data_source: string;
  readonly data_timestamp: string;
}

// ---------------------------------------------------------------------------
// Display types (camelCase -- for React components)
// ---------------------------------------------------------------------------

export type SentimentDirection = 'bullish' | 'bearish' | 'neutral';

/** Normalised article ready for rendering. */
export interface NewsArticle {
  readonly id: string;
  readonly headline: string;
  readonly summary: string;
  readonly source: string;
  readonly url: string | null;
  readonly imageUrl: string | null;
  readonly publishedAt: Date;
  readonly category: string | null;
  readonly relatedTickers: string[];
  readonly sentiment: SentimentDirection;
  readonly sentimentScore: number;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Number of articles to request per page. */
export const NEWS_PAGE_SIZE = 20;

/** Client-side cache TTL for page-1 results (5 minutes). */
export const NEWS_CACHE_TTL_MS = 300_000;

/** Delay before automatic retry on fetch error (5 seconds). */
export const NEWS_RETRY_DELAY_MS = 5_000;

/** Interval for updating relative timestamps (1 minute). */
export const RELATIVE_TIME_UPDATE_INTERVAL_MS = 60_000;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Parse a date string into a Date, returning epoch-zero on failure.
 * Guards against NaN dates from malformed or missing published_at values.
 */
function safeParseDate(value: string | null): Date {
  if (!value) return new Date(0);
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return new Date(0);
  return parsed;
}

/**
 * Normalise a raw backend article into the display format.
 *
 * Returns `null` for articles with no headline (nothing useful to show).
 * Defaults sentiment to 'neutral' with score 0.50 since the backend
 * currently returns `sentiment: null`.
 */
export function normalizeArticle(raw: NewsArticleRaw): NewsArticle | null {
  if (!raw.headline) return null;

  return {
    id: raw.id,
    headline: raw.headline,
    summary: raw.summary || '',
    source: raw.source || 'Unknown',
    url: raw.url,
    imageUrl: raw.image_url,
    publishedAt: safeParseDate(raw.published_at),
    category: raw.category,
    relatedTickers: Array.isArray(raw.related_tickers)
      ? raw.related_tickers
      : [],
    sentiment: (raw.sentiment as SentimentDirection) || 'neutral',
    sentimentScore: typeof raw.sentiment_score === 'number' ? raw.sentiment_score : 0.5,
  };
}

/**
 * Sort articles by publishedAt descending (most recent first).
 * Returns a new array; does not mutate the input.
 */
export function sortArticlesByDate(articles: NewsArticle[]): NewsArticle[] {
  return [...articles].sort(
    (a, b) => b.publishedAt.getTime() - a.publishedAt.getTime(),
  );
}

/**
 * Format a Date as a human-readable relative time string.
 *
 * Returns "just now" for < 60 s, "Xm ago", "Xh ago", "Xd ago", or "Xw ago".
 */
export function formatRelativeTime(date: Date): string {
  const now = Date.now();
  const diffMs = now - date.getTime();

  if (diffMs < 0) return 'just now';

  const seconds = Math.floor(diffMs / 1_000);
  if (seconds < 60) return 'just now';

  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m ago`;

  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;

  const days = Math.floor(hours / 24);
  if (days < 14) return `${days}d ago`;

  const weeks = Math.floor(days / 7);
  return `${weeks}w ago`;
}
