/**
 * Ownership & insider-trading types, constants, formatters, and normalizers.
 * Wire-format types match the backend /api/ownership/{symbol} and
 * /api/insider/{symbol} responses exactly.
 * @generated by code-generator (Agent #19)
 */

import { isDisplayable } from './fundamentals';
export { isDisplayable };

// ---------------------------------------------------------------------------
// Wire-format types (snake_case -- matches backend response)
// ---------------------------------------------------------------------------

/** Single institutional holder as returned by the backend. */
export interface OwnershipHolderRaw {
  readonly holder_name: string;
  readonly cik: string | null;
  readonly shares: number;
  readonly value: number;
  readonly percent_of_outstanding: number | null;
  readonly change_shares: number | null;
  readonly change_percent: number | null;
  readonly filing_date: string | null;
}

/** Quarter-over-quarter position changes as returned by the backend. */
export interface OwnershipQoQRaw {
  readonly new_positions: number;
  readonly increased_positions: number;
  readonly decreased_positions: number;
  readonly closed_positions: number;
  readonly net_shares_change: number;
}

/** Full envelope response from GET /api/ownership/{symbol}. */
export interface OwnershipApiResponse {
  readonly symbol: string;
  readonly filing_period: string | null;
  readonly total_institutional_shares: number;
  readonly total_institutional_value: number;
  readonly institutional_ownership_percent: number | null;
  readonly holders: OwnershipHolderRaw[];
  readonly quarter_over_quarter: OwnershipQoQRaw;
  readonly data_source: string;
  readonly data_timestamp: string;
  readonly note?: string;
}

/** Single insider transaction as returned by the backend. */
export interface InsiderTransactionRaw {
  readonly insider_name: string;
  readonly title: string | null;
  readonly transaction_type: string;
  readonly transaction_date: string | null;
  readonly shares: number;
  readonly price_per_share: number | null;
  readonly total_value: number | null;
  readonly shares_remaining: number | null;
  readonly filing_date: string | null;
  readonly filing_url: string | null;
}

/** Insider activity summary as returned by the backend. */
export interface InsiderSummaryRaw {
  readonly period_days: number;
  readonly total_insider_buys: number;
  readonly total_insider_sells: number;
  readonly total_buy_value: number;
  readonly total_sell_value: number;
  readonly net_activity: 'neutral' | 'net_buying' | 'net_selling';
  readonly buy_sell_ratio: number;
}

/** Full envelope response from GET /api/insider/{symbol}. */
export interface InsiderApiResponse {
  readonly symbol: string;
  readonly transactions: InsiderTransactionRaw[];
  readonly summary: InsiderSummaryRaw;
  readonly data_source: string;
  readonly data_timestamp: string;
}

// ---------------------------------------------------------------------------
// Display types (camelCase -- for React components)
// ---------------------------------------------------------------------------

/** Normalised institutional holder ready for rendering. */
export interface OwnershipHolder {
  readonly holderName: string;
  readonly cik: string | null;
  readonly shares: number;
  readonly value: number;
  readonly percentOfOutstanding: number | null;
  readonly changeShares: number | null;
  readonly changePercent: number | null;
  readonly filingDate: string | null;
}

/** Normalised quarter-over-quarter changes ready for rendering. */
export interface OwnershipQoQ {
  readonly newPositions: number;
  readonly increasedPositions: number;
  readonly decreasedPositions: number;
  readonly closedPositions: number;
  readonly netSharesChange: number;
}

/** Normalised ownership data ready for rendering. */
export interface OwnershipData {
  readonly symbol: string;
  readonly filingPeriod: string | null;
  readonly totalInstitutionalShares: number;
  readonly totalInstitutionalValue: number;
  readonly institutionalOwnershipPercent: number | null;
  readonly holders: OwnershipHolder[];
  readonly quarterOverQuarter: OwnershipQoQ;
  readonly dataSource: string;
  readonly dataTimestamp: string;
  readonly note: string;
}

/** Normalised insider transaction ready for rendering. */
export interface InsiderTransaction {
  readonly insiderName: string;
  readonly title: string | null;
  readonly transactionType: string;
  readonly transactionDate: string | null;
  readonly shares: number;
  readonly pricePerShare: number | null;
  readonly totalValue: number | null;
  readonly sharesRemaining: number | null;
  readonly filingDate: string | null;
}

/** Normalised insider activity summary ready for rendering. */
export interface InsiderSummary {
  readonly periodDays: number;
  readonly totalInsiderBuys: number;
  readonly totalInsiderSells: number;
  readonly totalBuyValue: number;
  readonly totalSellValue: number;
  readonly netActivity: 'neutral' | 'net_buying' | 'net_selling';
  readonly buySellRatio: number;
}

/** Normalised insider data ready for rendering. */
export interface InsiderData {
  readonly symbol: string;
  readonly transactions: InsiderTransaction[];
  readonly summary: InsiderSummary;
  readonly dataSource: string;
  readonly dataTimestamp: string;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Client-side cache TTL for ownership data (15 minutes). */
export const OWNERSHIP_CACHE_TTL_MS = 900_000;

/** Client-side cache TTL for insider data (15 minutes). */
export const INSIDER_CACHE_TTL_MS = 900_000;

/** Badge configuration keyed by backend transaction_type values. */
export const TRANSACTION_BADGE_MAP: Readonly<
  Record<string, { readonly label: string; readonly colorClass: string }>
> = {
  'P-Purchase': { label: 'Buy', colorClass: 'bg-accent-green' },
  'S-Sale': { label: 'Sell', colorClass: 'bg-accent-red' },
  'M-Exercise': { label: 'Exercise', colorClass: 'bg-accent-amber' },
  'G-Gift': { label: 'Gift', colorClass: 'bg-gray-600' },
  'A-Grant': { label: 'Grant', colorClass: 'bg-accent-blue' },
  'F-Tax': { label: 'Tax', colorClass: 'bg-gray-600' },
};

// ---------------------------------------------------------------------------
// Helpers -- sanitizers (private)
// ---------------------------------------------------------------------------

/**
 * Defensively coerce an unknown value to `number | null`.
 *
 * Returns the value as a number when it is a finite, non-boolean number;
 * returns `null` for everything else (including `NaN`, `Infinity`, booleans,
 * strings, objects, `undefined`, and `null`).
 */
function sanitizeNumber(value: unknown): number | null {
  if (typeof value === 'boolean') return null;
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  return null;
}

// ---------------------------------------------------------------------------
// Formatters
// ---------------------------------------------------------------------------

/**
 * Format a share count with K/M/B suffixes.
 *
 * - Returns `'--'` when the value is not displayable.
 * - Handles negative values correctly.
 * - Uses 2 decimal places after the suffix division.
 *
 * @example
 * formatShares(1_500_000)   // "1.50M"
 * formatShares(-2_300)      // "-2.30K"
 * formatShares(null)        // "--"
 */
export function formatShares(value: number | null): string {
  if (!isDisplayable(value)) return '--';
  const abs = Math.abs(value);
  if (abs >= 1e9) return `${(value / 1e9).toFixed(2)}B`;
  if (abs >= 1e6) return `${(value / 1e6).toFixed(2)}M`;
  if (abs >= 1e3) return `${(value / 1e3).toFixed(2)}K`;
  return new Intl.NumberFormat('en-US').format(value);
}

/**
 * Format a percentage change value with a leading sign.
 *
 * - Returns `'--'` when the value is not displayable.
 * - Prefixes positive values with `+`.
 *
 * @example
 * formatChangePercent(12.5)   // "+12.50%"
 * formatChangePercent(-3.2)   // "-3.20%"
 * formatChangePercent(null)   // "--"
 */
export function formatChangePercent(value: number | null): string {
  if (!isDisplayable(value)) return '--';
  const prefix = value > 0 ? '+' : '';
  return `${prefix}${value.toFixed(2)}%`;
}

// ---------------------------------------------------------------------------
// Normalizers
// ---------------------------------------------------------------------------

/**
 * Normalise a single raw holder record from snake_case to camelCase.
 *
 * Numeric fields are sanitized through `sanitizeNumber`; shares and value
 * default to 0 when absent or invalid.
 */
export function normalizeHolder(raw: OwnershipHolderRaw): OwnershipHolder {
  return {
    holderName: raw.holder_name,
    cik: raw.cik,
    shares: sanitizeNumber(raw.shares) ?? 0,
    value: sanitizeNumber(raw.value) ?? 0,
    percentOfOutstanding: sanitizeNumber(raw.percent_of_outstanding),
    changeShares: sanitizeNumber(raw.change_shares),
    changePercent: sanitizeNumber(raw.change_percent),
    filingDate: raw.filing_date,
  };
}

/**
 * Normalise the full ownership backend response into the display-ready format.
 *
 * - Maps all snake_case fields to camelCase.
 * - Guards `holders` against non-array values.
 * - Sanitizes every numeric field through `sanitizeNumber`.
 * - Defaults `note` to an empty string when absent.
 */
export function normalizeOwnership(raw: OwnershipApiResponse): OwnershipData {
  return {
    symbol: raw.symbol,
    filingPeriod: raw.filing_period,
    totalInstitutionalShares:
      sanitizeNumber(raw.total_institutional_shares) ?? 0,
    totalInstitutionalValue:
      sanitizeNumber(raw.total_institutional_value) ?? 0,
    institutionalOwnershipPercent: sanitizeNumber(
      raw.institutional_ownership_percent,
    ),
    holders: Array.isArray(raw.holders)
      ? raw.holders.map(normalizeHolder)
      : [],
    quarterOverQuarter: {
      newPositions:
        sanitizeNumber(raw.quarter_over_quarter.new_positions) ?? 0,
      increasedPositions:
        sanitizeNumber(raw.quarter_over_quarter.increased_positions) ?? 0,
      decreasedPositions:
        sanitizeNumber(raw.quarter_over_quarter.decreased_positions) ?? 0,
      closedPositions:
        sanitizeNumber(raw.quarter_over_quarter.closed_positions) ?? 0,
      netSharesChange:
        sanitizeNumber(raw.quarter_over_quarter.net_shares_change) ?? 0,
    },
    dataSource: raw.data_source,
    dataTimestamp: raw.data_timestamp,
    note: raw.note ?? '',
  };
}

/**
 * Normalise a single raw insider transaction from snake_case to camelCase.
 *
 * Numeric fields are sanitized; shares defaults to 0 when absent or invalid.
 * The `filing_url` field is intentionally dropped (always null from backend).
 */
export function normalizeInsiderTransaction(
  raw: InsiderTransactionRaw,
): InsiderTransaction {
  return {
    insiderName: raw.insider_name,
    title: raw.title,
    transactionType: raw.transaction_type,
    transactionDate: raw.transaction_date,
    shares: sanitizeNumber(raw.shares) ?? 0,
    pricePerShare: sanitizeNumber(raw.price_per_share),
    totalValue: sanitizeNumber(raw.total_value),
    sharesRemaining: sanitizeNumber(raw.shares_remaining),
    filingDate: raw.filing_date,
  };
}

/**
 * Normalise the full insider backend response into the display-ready format.
 *
 * - Maps all snake_case fields to camelCase.
 * - Guards `transactions` against non-array values.
 * - Sanitizes every numeric field through `sanitizeNumber`.
 */
export function normalizeInsider(raw: InsiderApiResponse): InsiderData {
  return {
    symbol: raw.symbol,
    transactions: Array.isArray(raw.transactions)
      ? raw.transactions.map(normalizeInsiderTransaction)
      : [],
    summary: {
      periodDays: sanitizeNumber(raw.summary.period_days) ?? 0,
      totalInsiderBuys: sanitizeNumber(raw.summary.total_insider_buys) ?? 0,
      totalInsiderSells:
        sanitizeNumber(raw.summary.total_insider_sells) ?? 0,
      totalBuyValue: sanitizeNumber(raw.summary.total_buy_value) ?? 0,
      totalSellValue: sanitizeNumber(raw.summary.total_sell_value) ?? 0,
      netActivity: raw.summary.net_activity,
      buySellRatio: sanitizeNumber(raw.summary.buy_sell_ratio) ?? 0,
    },
    dataSource: raw.data_source,
    dataTimestamp: raw.data_timestamp,
  };
}
