/**
 * Chart / ticker history types for OHLCV data and timeframe selection.
 * @generated by code-generator (Agent #19)
 */

export type Timeframe = '1d' | '1w' | '1m' | '3m' | '6m' | '1y' | '5y' | '1h' | '4h' | '8h' | '12h';

export const TIMEFRAMES: readonly Timeframe[] = [
  '1h',
  '4h',
  '8h',
  '12h',
  '1d',
  '1w',
  '1m',
  '3m',
  '6m',
  '1y',
  '5y',
] as const;

export const TIMEFRAME_LABELS: Readonly<Record<Timeframe, string>> = {
  '1h': '1H',
  '4h': '4H',
  '8h': '8H',
  '12h': '12H',
  '1d': '1D',
  '1w': '1W',
  '1m': '1M',
  '3m': '3M',
  '6m': '6M',
  '1y': '1Y',
  '5y': '5Y',
};

export const DEFAULT_TIMEFRAME: Timeframe = '1d';

/** Cache TTL for ticker history data (15 minutes). */
export const CACHE_TTL_MS = 900_000;

/** Single OHLCV bar for chart rendering. */
export interface OHLCVBar {
  readonly date: string; // "YYYY-MM-DD"
  readonly open: number;
  readonly high: number;
  readonly low: number;
  readonly close: number;
  readonly volume: number;
}

/** Price snapshot from the ticker endpoint. */
export interface TickerPrice {
  readonly current: number | null;
  readonly open: number | null;
  readonly high: number | null;
  readonly low: number | null;
  readonly previous_close: number | null;
  readonly change: number | null;
  readonly change_percent: number | null;
  readonly volume: number | null;
  readonly avg_volume_10d: number | null;
  readonly fifty_two_week_high: number | null;
  readonly fifty_two_week_low: number | null;
  readonly market_cap: number | null;
}

/** Full response from GET /api/ticker/{symbol}?include_history=true */
export interface TickerHistoryResponse {
  readonly symbol: string;
  readonly name: string | null;
  readonly exchange: string | null;
  readonly currency: string;
  readonly asset_type: string;
  readonly price: TickerPrice;
  readonly data_source: string;
  readonly data_timestamp: string;
  readonly data_age_seconds: number;
  readonly is_market_open: boolean;
  readonly cache_hit: boolean;
  readonly ohlcv: OHLCVBar[];
}
