/**
 * Watchlist types and constants for the watchlist panel component.
 * @generated by code-generator (Agent #19)
 */

/** Valid ticker symbol pattern: 1-5 uppercase letters. */
export const SYMBOL_REGEX = /^[A-Z]{1,5}$/;

/** Maximum number of tickers allowed in a watchlist. */
export const MAX_WATCHLIST_SIZE = 50;

/** A single entry in the watchlist, as returned by the backend. */
export interface WatchlistEntry {
  readonly symbol: string;
  readonly group: string;
  readonly added_at: string;
  readonly position: number;
  readonly last_price: number | null;
  readonly price_change_percent: number | null;
  readonly last_composite_signal: string | null;
  readonly last_composite_confidence: number | null;
  readonly last_updated: string | null;
}

/** Full response from GET /api/watchlist. */
export interface WatchlistResponse {
  readonly tickers: WatchlistEntry[];
  readonly count: number;
  readonly max_allowed: number;
  readonly groups: string[];
}
