/**
 * Custom hook for fetching fundamentals data with client-side caching.
 * Follows the same cancelled-flag pattern as useTickerChart.ts.
 * @generated by unit-implementer (Agent #21)
 */
import { useState, useEffect } from 'react';
import { getFundamentals } from '../api/client';
import type { FundamentalsData, FundamentalsApiResponse } from '../types/fundamentals';
import {
  FUNDAMENTALS_CACHE_TTL_MS,
  normalizeFundamentals,
} from '../types/fundamentals';

interface CacheEntry {
  readonly data: FundamentalsData;
  readonly timestamp: number;
}

/** Module-level cache keyed by uppercase symbol. */
const cache = new Map<string, CacheEntry>();

export interface UseFundamentalsResult {
  readonly data: FundamentalsData | null;
  readonly loading: boolean;
  readonly error: string | null;
}

/**
 * Clear the fundamentals cache. Useful for testing or force-refresh.
 */
export function clearFundamentalsCache(): void {
  cache.clear();
}

/**
 * Fetch fundamentals data for a given symbol.
 *
 * - Returns null data when symbol is empty (no fetch).
 * - Serves from a 15-minute client-side cache when available.
 * - Normalises snake_case backend response to camelCase via normalizeFundamentals.
 * - Uses safe static error messages (no XSS -- never reflects user input).
 * - No auto-retry on failure.
 *
 * @param symbol - Ticker symbol (e.g. "AAPL")
 */
export function useFundamentals(symbol: string): UseFundamentalsResult {
  const [data, setData] = useState<FundamentalsData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!symbol) {
      setData(null);
      setError(null);
      setLoading(false);
      return;
    }

    const key = symbol.toUpperCase();

    // Check cache first
    const cached = cache.get(key);
    if (cached && Date.now() - cached.timestamp < FUNDAMENTALS_CACHE_TTL_MS) {
      setData(cached.data);
      setError(null);
      setLoading(false);
      return;
    }

    let cancelled = false;
    setLoading(true);
    setError(null);

    getFundamentals(key)
      .then((raw: FundamentalsApiResponse) => {
        if (cancelled) return;

        const normalized = normalizeFundamentals(raw);
        cache.set(key, { data: normalized, timestamp: Date.now() });
        setData(normalized);
        setError(null);
      })
      .catch(() => {
        if (cancelled) return;
        setData(null);
        // Static error message -- NEVER reflect user input (XSS prevention)
        setError('Failed to load fundamentals data. Please try again later.');
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [symbol]);

  return { data, loading, error };
}
