/**
 * Custom hook for fetching ticker OHLCV chart data with client-side caching.
 * Follows the same cancelled-flag pattern as useTicker.ts.
 * @generated by code-generator (Agent #19)
 */
import { useEffect, useState } from 'react';
import type { OHLCVBar, Timeframe } from '../types/ticker';
import { CACHE_TTL_MS, DEFAULT_TIMEFRAME } from '../types/ticker';
import { getTickerHistory } from '../api/client';

interface CacheEntry {
  readonly bars: OHLCVBar[];
  readonly timestamp: number;
}

/** Module-level cache keyed by "SYMBOL:TIMEFRAME". */
const cache = new Map<string, CacheEntry>();

/**
 * Minimal date-string format check: must match YYYY-MM-DD (or YYYY-MM-DDTHH...)
 * to prevent malformed strings from reaching the charting library.
 */
const DATE_PREFIX_RE = /^\d{4}-\d{2}-\d{2}/;

/**
 * Check whether a single OHLCV bar has all required fields with valid values.
 *
 * Validates:
 * - `date` is a non-empty string matching YYYY-MM-DD format
 * - `open`, `high`, `low`, `close` are finite numbers
 * - `volume` is a finite, non-negative number
 */
function isValidBar(bar: unknown): bar is OHLCVBar {
  if (bar === null || typeof bar !== 'object') return false;
  const b = bar as Record<string, unknown>;
  return (
    typeof b.date === 'string' &&
    DATE_PREFIX_RE.test(b.date) &&
    typeof b.open === 'number' &&
    Number.isFinite(b.open) &&
    typeof b.high === 'number' &&
    Number.isFinite(b.high) &&
    typeof b.low === 'number' &&
    Number.isFinite(b.low) &&
    typeof b.close === 'number' &&
    Number.isFinite(b.close) &&
    typeof b.volume === 'number' &&
    Number.isFinite(b.volume) &&
    b.volume >= 0
  );
}

export interface UseTickerChartResult {
  readonly bars: OHLCVBar[];
  readonly loading: boolean;
  readonly error: string | null;
}

/**
 * Fetch OHLCV bars for a given symbol and timeframe.
 *
 * - Returns empty bars when symbol is empty (no fetch).
 * - Serves from a 15-minute client-side cache when available.
 * - Sanitises bars with Number.isFinite checks.
 * - Uses safe static error messages (no XSS -- never reflects user input).
 *
 * @param symbol - Uppercase ticker symbol
 * @param timeframe - Chart timeframe period
 */
export function useTickerChart(
  symbol: string,
  initialTimeframe?: Timeframe,
): UseTickerChartResult {
  const timeframe = initialTimeframe ?? DEFAULT_TIMEFRAME;
  const [bars, setBars] = useState<OHLCVBar[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!symbol) {
      setBars([]);
      setError(null);
      setLoading(false);
      return;
    }

    const cacheKey = `${symbol.toUpperCase()}:${timeframe}`;
    const cached = cache.get(cacheKey);
    const now = Date.now();

    if (cached && now - cached.timestamp < CACHE_TTL_MS) {
      setBars(cached.bars);
      setError(null);
      setLoading(false);
      return;
    }

    let cancelled = false;
    setLoading(true);
    setError(null);

    getTickerHistory(symbol, timeframe)
      .then((result) => {
        if (cancelled) return;

        const validBars = Array.isArray(result.ohlcv)
          ? result.ohlcv.filter(isValidBar)
          : [];

        cache.set(cacheKey, { bars: validBars, timestamp: Date.now() });
        setBars(validBars);
      })
      .catch(() => {
        if (cancelled) return;
        setError('Failed to load chart data. Please try again.');
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [symbol, timeframe]);

  return { bars, loading, error };
}

/**
 * Clear the ticker chart cache. Useful for testing or force-refresh.
 */
export function clearTickerChartCache(): void {
  cache.clear();
}
