/**
 * DAI-002: Coding Pipeline Agent Mappings - Phases 4-7
 *
 * Phase 4: Implementation (12 agents + Sherlock #44)
 * Phase 5: Testing (7 agents + Sherlock #45)
 * Phase 6: Optimization (5 agents + Sherlock #46)
 * Phase 7: Delivery (1 agent + Sherlock #47)
 *
 * Total: 25 core agents + 4 Sherlock = 29 agents in this file.
 *
 * Extracted for constitution compliance (< 500 lines per file).
 *
 * @see command-task-bridge.ts
 * @see SPEC-001-architecture.md
 * @see constitution.xml
 */

import type { IAgentMapping as ICodingAgentMapping } from './types.js';

/**
 * Phase 4-7 agent mappings (29 agents total).
 *
 * Phase 4: Implementation (13 agents including Sherlock)
 * Phase 5: Testing (8 agents including Sherlock)
 * Phase 6: Optimization (6 agents including Sherlock)
 * Phase 7: Delivery (2 agents including Sherlock)
 */
export const CODING_PIPELINE_MAPPINGS_PHASE_4_7: ICodingAgentMapping[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // PHASE 4: IMPLEMENTATION (12 agents)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    phase: 'implementation',
    agentKey: 'code-generator',
    priority: 1,
    category: 'implementation',
    algorithm: 'Self-Debug',
    fallbackAlgorithm: 'ReAct',
    dependsOn: ['integration-architect'],
    memoryReads: ['coding/architecture/design', 'coding/architecture/interfaces'],
    memoryWrites: ['coding/implementation/generated-code', 'coding/implementation/core-files'],
    xpReward: 70,
    parallelizable: false,
    critical: false,
    description: 'Generates clean, production-ready code following architecture specifications.',
  },
  {
    phase: 'implementation',
    agentKey: 'type-implementer',
    priority: 2,
    category: 'implementation',
    algorithm: 'Self-Debug',
    fallbackAlgorithm: 'ReAct',
    dependsOn: ['code-generator'],
    memoryReads: ['coding/architecture/interfaces', 'coding/implementation/generated-code'],
    memoryWrites: ['coding/implementation/types', 'coding/implementation/type-files'],
    xpReward: 55,
    parallelizable: true,
    critical: false,
    description: 'Implements TypeScript type definitions, interfaces, generics, and type utilities.',
  },
  {
    phase: 'implementation',
    agentKey: 'unit-implementer',
    priority: 3,
    category: 'implementation',
    algorithm: 'Self-Debug',
    fallbackAlgorithm: 'Reflexion',
    dependsOn: ['type-implementer'],
    memoryReads: ['coding/implementation/types', 'coding/architecture/components'],
    memoryWrites: ['coding/implementation/units', 'coding/implementation/entities'],
    xpReward: 55,
    parallelizable: true,
    critical: false,
    description: 'Implements domain entities, value objects, and core business logic units.',
  },
  {
    phase: 'implementation',
    agentKey: 'service-implementer',
    priority: 4,
    category: 'implementation',
    algorithm: 'LATS',
    fallbackAlgorithm: 'Self-Debug',
    dependsOn: ['unit-implementer'],
    memoryReads: ['coding/implementation/units', 'coding/architecture/design'],
    memoryWrites: ['coding/implementation/services', 'coding/implementation/business-logic'],
    xpReward: 60,
    parallelizable: false,
    critical: false,
    description: 'Implements domain services, business logic, and application use cases.',
  },
  {
    phase: 'implementation',
    agentKey: 'data-layer-implementer',
    priority: 5,
    category: 'implementation',
    algorithm: 'Self-Debug',
    fallbackAlgorithm: 'ReAct',
    dependsOn: ['unit-implementer'],
    memoryReads: ['coding/implementation/units', 'coding/architecture/data-models'],
    memoryWrites: ['coding/implementation/data-layer', 'coding/implementation/repositories'],
    xpReward: 55,
    parallelizable: true,
    critical: false,
    description: 'Implements repositories, database access, and data persistence layer.',
  },
  {
    phase: 'implementation',
    agentKey: 'api-implementer',
    priority: 6,
    category: 'implementation',
    algorithm: 'ReAct',
    fallbackAlgorithm: 'Self-Debug',
    dependsOn: ['service-implementer', 'data-layer-implementer'],
    memoryReads: ['coding/implementation/services', 'coding/architecture/interfaces'],
    memoryWrites: ['coding/implementation/api', 'coding/implementation/endpoints'],
    xpReward: 60,
    parallelizable: false,
    critical: false,
    description: 'Implements REST/GraphQL API endpoints, controllers, and request validation.',
  },
  {
    phase: 'implementation',
    agentKey: 'frontend-implementer',
    priority: 7,
    category: 'implementation',
    algorithm: 'Self-Debug',
    fallbackAlgorithm: 'ReAct',
    dependsOn: ['api-implementer'],
    memoryReads: ['coding/implementation/api', 'coding/architecture/components'],
    memoryWrites: ['coding/implementation/frontend', 'coding/implementation/ui-components'],
    xpReward: 55,
    parallelizable: true,
    critical: false,
    description: 'Implements UI components, pages, state management, and client-side logic.',
  },
  {
    phase: 'implementation',
    agentKey: 'error-handler-implementer',
    priority: 8,
    category: 'implementation',
    algorithm: 'ReAct',
    fallbackAlgorithm: 'Reflexion',
    dependsOn: ['api-implementer'],
    memoryReads: ['coding/implementation/api', 'coding/implementation/services'],
    memoryWrites: ['coding/implementation/error-handling', 'coding/implementation/exceptions'],
    xpReward: 50,
    parallelizable: true,
    critical: false,
    description: 'Implements error handling strategies, recovery mechanisms, and error reporting.',
  },
  {
    phase: 'implementation',
    agentKey: 'config-implementer',
    priority: 9,
    category: 'implementation',
    algorithm: 'ReAct',
    fallbackAlgorithm: 'Self-Debug',
    dependsOn: ['frontend-implementer'],
    memoryReads: ['coding/implementation/api', 'coding/architecture/dependencies'],
    memoryWrites: ['coding/implementation/config', 'coding/implementation/settings'],
    xpReward: 40,
    parallelizable: true,
    critical: false,
    description: 'Implements configuration management, environment handling, and feature flags.',
  },
  {
    phase: 'implementation',
    agentKey: 'logger-implementer',
    priority: 10,
    category: 'implementation',
    algorithm: 'ReAct',
    fallbackAlgorithm: 'Self-Debug',
    dependsOn: ['error-handler-implementer'],
    memoryReads: ['coding/implementation/error-handling', 'coding/implementation/services'],
    memoryWrites: ['coding/implementation/logging', 'coding/implementation/observability'],
    xpReward: 45,
    parallelizable: true,
    critical: false,
    description: 'Implements logging infrastructure, log formatting, and observability patterns.',
  },
  {
    phase: 'implementation',
    agentKey: 'dependency-manager',
    priority: 11,
    category: 'implementation',
    algorithm: 'ReAct',
    fallbackAlgorithm: 'Self-Debug',
    dependsOn: ['config-implementer', 'logger-implementer'],
    memoryReads: ['coding/implementation/config', 'coding/architecture/dependencies'],
    memoryWrites: ['coding/implementation/dependencies', 'coding/implementation/package-json'],
    xpReward: 40,
    parallelizable: false,
    critical: false,
    description: 'Manages package dependencies, version resolution, and module organization.',
  },
  {
    phase: 'implementation',
    agentKey: 'implementation-coordinator',
    priority: 12,
    category: 'implementation',
    algorithm: 'Reflexion',
    fallbackAlgorithm: 'ReAct',
    dependsOn: ['dependency-manager'],
    memoryReads: ['coding/implementation/generated-code', 'coding/implementation/services', 'coding/implementation/api'],
    memoryWrites: ['coding/implementation/coordination-report', 'coding/implementation/integration-status'],
    xpReward: 55,
    parallelizable: false,
    critical: false,
    description: 'Coordinates implementation across all agents, manages dependencies, and ensures consistency.',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PHASE 5: TESTING (7 agents)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    phase: 'testing',
    agentKey: 'test-generator',
    priority: 1,
    category: 'testing',
    algorithm: 'ToT',
    fallbackAlgorithm: 'Self-Debug',
    dependsOn: ['implementation-coordinator'],
    memoryReads: ['coding/implementation/services', 'coding/understanding/requirements'],
    memoryWrites: ['coding/testing/generated-tests', 'coding/testing/test-files'],
    xpReward: 55,
    parallelizable: false,
    critical: false,
    description: 'Generates comprehensive test suites including unit, integration, and e2e tests.',
  },
  {
    phase: 'testing',
    agentKey: 'test-runner',
    priority: 2,
    category: 'testing',
    algorithm: 'ReAct',
    fallbackAlgorithm: 'Self-Debug',
    dependsOn: ['test-generator'],
    memoryReads: ['coding/testing/generated-tests', 'coding/implementation/services'],
    memoryWrites: ['coding/testing/results', 'coding/testing/failures'],
    xpReward: 50,
    parallelizable: false,
    critical: false,
    description: 'Orchestrates and executes all test suites, managing test lifecycle and reporting results.',
  },
  {
    phase: 'testing',
    agentKey: 'integration-tester',
    priority: 3,
    category: 'testing',
    algorithm: 'Self-Debug',
    fallbackAlgorithm: 'ReAct',
    dependsOn: ['test-runner'],
    memoryReads: ['coding/testing/results', 'coding/implementation/api'],
    memoryWrites: ['coding/testing/integration-tests', 'coding/testing/integration-results'],
    xpReward: 55,
    parallelizable: true,
    critical: false,
    description: 'Creates and executes integration tests verifying component interactions and system behavior.',
  },
  {
    phase: 'testing',
    agentKey: 'regression-tester',
    priority: 4,
    category: 'testing',
    algorithm: 'Reflexion',
    fallbackAlgorithm: 'Self-Debug',
    dependsOn: ['test-runner'],
    memoryReads: ['coding/testing/results', 'coding/understanding/context'],
    memoryWrites: ['coding/testing/regression-tests', 'coding/testing/breaking-changes'],
    xpReward: 50,
    parallelizable: true,
    critical: false,
    description: 'Performs regression testing to detect unintended changes and compares against baselines.',
  },
  {
    phase: 'testing',
    agentKey: 'security-tester',
    priority: 5,
    category: 'testing',
    algorithm: 'ReAct',
    fallbackAlgorithm: 'Reflexion',
    dependsOn: ['integration-tester'],
    memoryReads: ['coding/testing/integration-results', 'coding/implementation/api'],
    memoryWrites: ['coding/testing/security-tests', 'coding/testing/vulnerabilities'],
    xpReward: 60,
    parallelizable: true,
    critical: false,
    description: 'Performs security testing including vulnerability scanning and compliance verification.',
  },
  {
    phase: 'testing',
    agentKey: 'coverage-analyzer',
    priority: 6,
    category: 'testing',
    algorithm: 'PoT',
    fallbackAlgorithm: 'ReAct',
    dependsOn: ['regression-tester', 'security-tester'],
    memoryReads: ['coding/testing/results', 'coding/testing/integration-results'],
    memoryWrites: ['coding/testing/coverage-report', 'coding/testing/coverage-gaps'],
    xpReward: 50,
    parallelizable: false,
    critical: false,
    description: 'Analyzes test coverage metrics, identifies gaps, and generates coverage reports.',
  },
  {
    phase: 'testing',
    agentKey: 'quality-gate',
    priority: 7,
    category: 'testing',
    algorithm: 'Reflexion',
    fallbackAlgorithm: 'PoT',
    dependsOn: ['coverage-analyzer'],
    memoryReads: ['coding/testing/coverage-report', 'coding/testing/results'],
    memoryWrites: ['coding/testing/quality-verdict', 'coding/testing/l-score'],
    xpReward: 65,
    parallelizable: false,
    critical: true,
    description: 'Validates code against quality gates, computes L-Scores, and determines phase completion.',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PHASE 6: OPTIMIZATION (5 agents)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    phase: 'optimization',
    agentKey: 'performance-optimizer',
    priority: 1,
    category: 'optimization',
    algorithm: 'PoT',
    fallbackAlgorithm: 'Reflexion',
    dependsOn: ['quality-gate'],
    memoryReads: ['coding/implementation/services', 'coding/testing/results'],
    memoryWrites: ['coding/optimization/performance', 'coding/optimization/benchmarks'],
    xpReward: 60,
    parallelizable: false,
    critical: false,
    description: 'Identifies and optimizes performance bottlenecks, memory usage, and runtime efficiency.',
  },
  {
    phase: 'optimization',
    agentKey: 'performance-architect',
    priority: 2,
    category: 'optimization',
    algorithm: 'ToT',
    fallbackAlgorithm: 'ReAct',
    dependsOn: ['performance-optimizer'],
    memoryReads: ['coding/optimization/performance', 'coding/architecture/design'],
    memoryWrites: ['coding/optimization/architecture-improvements', 'coding/optimization/scalability'],
    xpReward: 55,
    parallelizable: true,
    critical: false,
    description: 'Designs performance architecture, optimization strategies, and scalability patterns.',
  },
  {
    phase: 'optimization',
    agentKey: 'code-quality-improver',
    priority: 3,
    category: 'optimization',
    algorithm: 'Reflexion',
    fallbackAlgorithm: 'ReAct',
    dependsOn: ['performance-optimizer'],
    memoryReads: ['coding/implementation/services', 'coding/testing/quality-verdict'],
    memoryWrites: ['coding/optimization/quality-improvements', 'coding/optimization/refactoring'],
    xpReward: 50,
    parallelizable: true,
    critical: false,
    description: 'Improves code quality through refactoring, pattern application, and maintainability enhancements.',
  },
  {
    phase: 'optimization',
    agentKey: 'security-architect',
    priority: 4,
    category: 'security',
    algorithm: 'ReAct',
    fallbackAlgorithm: 'Reflexion',
    dependsOn: ['performance-architect', 'code-quality-improver'],
    memoryReads: ['coding/testing/vulnerabilities', 'coding/implementation/api'],
    memoryWrites: ['coding/optimization/security-improvements', 'coding/optimization/security-audit'],
    xpReward: 60,
    parallelizable: false,
    critical: false,
    description: 'Designs security architecture, authentication flows, and threat mitigation strategies.',
  },
  {
    phase: 'optimization',
    agentKey: 'final-refactorer',
    priority: 5,
    category: 'optimization',
    algorithm: 'Reflexion',
    fallbackAlgorithm: 'Self-Debug',
    dependsOn: ['security-architect'],
    memoryReads: ['coding/optimization/quality-improvements', 'coding/optimization/security-audit'],
    memoryWrites: ['coding/optimization/final-code', 'coding/optimization/polish-report'],
    xpReward: 55,
    parallelizable: false,
    critical: false,
    description: 'Performs final code polish, consistency checks, and prepares code for delivery.',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PHASE 7: DELIVERY (1 core agent)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    phase: 'delivery',
    agentKey: 'sign-off-approver',
    priority: 1,
    category: 'approval',
    algorithm: 'Reflexion',
    fallbackAlgorithm: 'ReAct',
    dependsOn: ['final-refactorer'],
    memoryReads: ['coding/optimization/final-code', 'coding/testing/coverage-report', 'coding/testing/quality-verdict'],
    memoryWrites: ['coding/delivery/sign-off', 'coding/delivery/approval-status'],
    xpReward: 75,
    parallelizable: false,
    critical: true,
    description: 'Final sign-off authority for code delivery, verifying all requirements met. CRITICAL: Must pass for pipeline completion.',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SHERLOCK FORENSIC REVIEW AGENTS (#44-47)
  // Phase 4-7 forensic reviewers - CRITICAL: Gates phase progression
  // ═══════════════════════════════════════════════════════════════════════════

  // #44 - Phase 4 Implementation Forensic Review
  {
    phase: 'implementation',
    agentKey: 'phase-4-reviewer',
    priority: 99,
    category: 'forensic-review',
    algorithm: 'Reflexion',
    fallbackAlgorithm: 'Self-Debug',
    dependsOn: ['implementation-coordinator'],
    memoryReads: [
      'coding/implementation/generated-code',
      'coding/implementation/types',
      'coding/implementation/services',
      'coding/implementation/api',
      'coding/implementation/coordination-report',
    ],
    memoryWrites: ['coding/forensic/phase-4-verdict', 'coding/forensic/phase-4-evidence'],
    xpReward: 100,
    parallelizable: false,
    critical: true,
    description: 'Sherlock #44: Phase 4 Implementation forensic review. CRITICAL: Gates progression to Phase 5.',
  },

  // #45 - Phase 5 Testing Forensic Review
  {
    phase: 'testing',
    agentKey: 'phase-5-reviewer',
    priority: 99,
    category: 'forensic-review',
    algorithm: 'Reflexion',
    fallbackAlgorithm: 'Self-Debug',
    dependsOn: ['quality-gate'],
    memoryReads: [
      'coding/testing/generated-tests',
      'coding/testing/results',
      'coding/testing/coverage-report',
      'coding/testing/quality-verdict',
    ],
    memoryWrites: ['coding/forensic/phase-5-verdict', 'coding/forensic/phase-5-evidence'],
    xpReward: 100,
    parallelizable: false,
    critical: true,
    description: 'Sherlock #45: Phase 5 Testing forensic review. CRITICAL: Gates progression to Phase 6.',
  },

  // #46 - Phase 6 Optimization Forensic Review
  {
    phase: 'optimization',
    agentKey: 'phase-6-reviewer',
    priority: 99,
    category: 'forensic-review',
    algorithm: 'Reflexion',
    fallbackAlgorithm: 'ToT',
    dependsOn: ['final-refactorer'],
    memoryReads: [
      'coding/optimization/performance',
      'coding/optimization/quality-improvements',
      'coding/optimization/security-audit',
      'coding/optimization/final-code',
    ],
    memoryWrites: ['coding/forensic/phase-6-verdict', 'coding/forensic/phase-6-evidence'],
    xpReward: 100,
    parallelizable: false,
    critical: true,
    description: 'Sherlock #46: Phase 6 Optimization forensic review. CRITICAL: Gates progression to Phase 7.',
  },

  // #47 - Phase 7 Delivery Forensic Review / Recovery Agent
  {
    phase: 'delivery',
    agentKey: 'recovery-agent',
    priority: 99,
    category: 'forensic-review',
    algorithm: 'Reflexion',
    fallbackAlgorithm: 'LATS',
    dependsOn: ['sign-off-approver'],
    memoryReads: [
      'coding/delivery/sign-off',
      'coding/forensic/phase-1-verdict',
      'coding/forensic/phase-2-verdict',
      'coding/forensic/phase-3-verdict',
      'coding/forensic/phase-4-verdict',
      'coding/forensic/phase-5-verdict',
      'coding/forensic/phase-6-verdict',
    ],
    memoryWrites: ['coding/forensic/phase-7-verdict', 'coding/forensic/final-report', 'coding/forensic/recovery-plan'],
    xpReward: 150,
    parallelizable: false,
    critical: true,
    description: 'Sherlock #47: Phase 7 Delivery forensic review and recovery orchestration. CRITICAL: Final pipeline gate.',
  },
];
