/**
 * Real-time analysis pipeline progress display.
 * Subscribes to the analysis_progress WebSocket channel and shows per-symbol
 * progress bars with agent status, elapsed time, and auto-dismiss on completion.
 * @generated by unit-implementer (Agent #21)
 */
import { useCallback, useEffect, useRef, useState } from 'react';
import { useWebSocketContext } from '../contexts/WebSocketContext';
import { WS_CHANNELS } from '../types/websocket';
import type {
  WsAnalysisProgressMessage,
  WsAnalysisCompleteMessage,
} from '../types/websocket';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface AnalysisProgressProps {
  /** When set, only display progress for this symbol. */
  readonly symbol?: string;
}

interface ProgressState {
  readonly symbol: string;
  readonly agent: string;
  readonly agentNumber: number;
  readonly totalAgents: number;
  readonly status: 'running' | 'completed' | 'failed';
  readonly message: string;
  readonly startedAt: number;
  readonly completedAt: number | null;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Format elapsed milliseconds as "Ns" or "Nm Ns". */
function formatElapsed(ms: number): string {
  const totalSeconds = Math.max(0, Math.floor(ms / 1000));
  if (totalSeconds < 60) {
    return `${totalSeconds}s`;
  }
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return `${minutes}m ${seconds}s`;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function AnalysisProgress({ symbol }: AnalysisProgressProps) {
  const { subscribe, unsubscribe, onMessage } = useWebSocketContext();

  const [progressMap, setProgressMap] = useState<Map<string, ProgressState>>(
    () => new Map(),
  );

  // Track auto-dismiss timers so we can clean them up on unmount.
  const dismissTimersRef = useRef<Map<string, ReturnType<typeof setTimeout>>>(
    new Map(),
  );

  // Force a re-render every second so elapsed time updates while running.
  const [, setTick] = useState(0);
  const tickTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // Start/stop the tick timer based on whether we have active (non-completed) entries.
  useEffect(() => {
    const hasActive = Array.from(progressMap.values()).some(
      (p) => p.completedAt === null,
    );

    if (hasActive && tickTimerRef.current === null) {
      tickTimerRef.current = setInterval(() => {
        setTick((prev) => prev + 1);
      }, 1000);
    } else if (!hasActive && tickTimerRef.current !== null) {
      clearInterval(tickTimerRef.current);
      tickTimerRef.current = null;
    }

    return () => {
      // Cleanup handled in the unmount effect below.
    };
  }, [progressMap]);

  // Schedule auto-dismiss for a completed symbol.
  const scheduleDismiss = useCallback((sym: string) => {
    // Clear any existing timer for this symbol.
    const existing = dismissTimersRef.current.get(sym);
    if (existing !== undefined) {
      clearTimeout(existing);
    }

    const timer = setTimeout(() => {
      dismissTimersRef.current.delete(sym);
      setProgressMap((prev) => {
        const next = new Map(prev);
        next.delete(sym);
        return next;
      });
    }, 2000);

    dismissTimersRef.current.set(sym, timer);
  }, []);

  // Subscribe to channel and register listeners.
  useEffect(() => {
    subscribe(WS_CHANNELS.AnalysisProgress);

    const removeProgress = onMessage(
      'analysis_progress',
      (msg: WsAnalysisProgressMessage) => {
        // Filter by symbol prop when provided.
        if (symbol !== undefined && msg.symbol !== symbol) return;

        setProgressMap((prev) => {
          const next = new Map(prev);
          const existing = prev.get(msg.symbol);
          next.set(msg.symbol, {
            symbol: msg.symbol,
            agent: msg.agent,
            agentNumber: msg.agent_number,
            totalAgents: msg.total_agents,
            status: msg.status,
            message: msg.message,
            startedAt: existing?.startedAt ?? Date.now(),
            completedAt: null,
          });
          return next;
        });
      },
    );

    const removeComplete = onMessage(
      'analysis_complete',
      (msg: WsAnalysisCompleteMessage) => {
        // Filter by symbol prop when provided.
        if (symbol !== undefined && msg.symbol !== symbol) return;

        setProgressMap((prev) => {
          const existing = prev.get(msg.symbol);
          if (!existing) return prev;

          const next = new Map(prev);
          next.set(msg.symbol, {
            ...existing,
            status: 'completed',
            completedAt: Date.now(),
          });
          return next;
        });

        scheduleDismiss(msg.symbol);
      },
    );

    return () => {
      removeProgress();
      removeComplete();
      unsubscribe(WS_CHANNELS.AnalysisProgress);
    };
  }, [symbol, subscribe, unsubscribe, onMessage, scheduleDismiss]);

  // Cleanup all timers on unmount.
  useEffect(() => {
    return () => {
      if (tickTimerRef.current !== null) {
        clearInterval(tickTimerRef.current);
        tickTimerRef.current = null;
      }
      dismissTimersRef.current.forEach((timer) => clearTimeout(timer));
      dismissTimersRef.current.clear();
    };
  }, []);

  // -- Render ---------------------------------------------------------------

  if (progressMap.size === 0) {
    return null;
  }

  const entries = Array.from(progressMap.values());

  return (
    <div
      className="bg-terminal-panel border border-terminal-border rounded p-4"
      data-testid="analysis-progress"
    >
      <h3 className="text-text-primary font-mono text-sm mb-3">
        Analysis Progress
      </h3>

      <div className="space-y-3">
        {entries.map((entry) => {
          const isCompleted = entry.completedAt !== null;
          const percent =
            entry.totalAgents > 0
              ? Math.round((entry.agentNumber / entry.totalAgents) * 100)
              : 0;
          const elapsed = isCompleted
            ? entry.completedAt! - entry.startedAt
            : Date.now() - entry.startedAt;

          return (
            <div key={entry.symbol} className="space-y-1">
              {/* Symbol header row */}
              <div className="flex items-center justify-between">
                <span className="text-accent-amber font-mono text-xs font-bold">
                  {entry.symbol}
                </span>
                <span className="text-text-secondary font-mono text-xs">
                  {formatElapsed(elapsed)}
                </span>
              </div>

              {/* Progress bar */}
              <div className="w-full bg-terminal-border rounded-full h-1.5">
                <div
                  className={`h-1.5 rounded-full transition-all duration-300 ${
                    isCompleted ? 'bg-green-500' : 'bg-accent-amber'
                  }`}
                  style={{ width: `${isCompleted ? 100 : percent}%` }}
                  data-testid={`progress-bar-${entry.symbol}`}
                />
              </div>

              {/* Status text */}
              <p
                className={`font-mono text-xs ${
                  isCompleted ? 'text-green-400' : 'text-text-secondary'
                }`}
              >
                {isCompleted
                  ? 'Analysis complete'
                  : `Agent ${entry.agentNumber}/${entry.totalAgents}: ${entry.message}`}
              </p>
            </div>
          );
        })}
      </div>
    </div>
  );
}
