/**
 * Fundamentals panel displaying TTM metrics, quarterly filings, and key ratios
 * for the active ticker symbol. Follows terminal dark-theme conventions.
 * @generated by service-implementer (Agent #22)
 */
import type { FundamentalsTtm, FundamentalsQuarter } from '../types/fundamentals';
import {
  isDisplayable,
  formatCurrency,
  formatPercent,
  formatRatio,
  formatEps,
} from '../types/fundamentals';
import { useFundamentals } from '../hooks/useFundamentals';

// ---------------------------------------------------------------------------
// Internal sub-components (not exported)
// ---------------------------------------------------------------------------

/** Animated placeholder bars while data is loading. */
function LoadingSkeleton() {
  return (
    <div className="space-y-3">
      {/* 2x4 grid placeholder */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
        {[0, 1, 2, 3, 4, 5, 6, 7].map((i) => (
          <div key={i} className="space-y-1">
            <div className="h-2 animate-pulse bg-terminal-border rounded w-16" />
            <div className="h-3 animate-pulse bg-terminal-border rounded w-20" />
          </div>
        ))}
      </div>
      {/* Table row placeholders */}
      {[0, 1, 2, 3].map((i) => (
        <div key={`row-${i}`} className="h-4 animate-pulse bg-terminal-border rounded w-full" />
      ))}
      {/* Ratio row placeholders */}
      {[0, 1, 2].map((i) => (
        <div key={`ratio-${i}`} className="h-3 animate-pulse bg-terminal-border rounded w-3/4" />
      ))}
    </div>
  );
}

/** Red error text, static message only (XSS prevention). */
function ErrorState({ message }: { readonly message: string }) {
  return (
    <p className="text-accent-red text-xs text-center py-4">{message}</p>
  );
}

/** Static empty-state message. Never interpolates user input. */
function EmptyState() {
  return (
    <p className="text-text-muted text-xs text-center py-4">
      No fundamental data available
    </p>
  );
}

/** Vertical label + value cell for the key metrics grid. */
function MetricCell({
  label,
  value,
}: {
  readonly label: string;
  readonly value: string;
}) {
  return (
    <div>
      <div className="text-text-muted text-xs">{label}</div>
      <div className="text-text-primary font-mono text-sm">{value}</div>
    </div>
  );
}

/** 2x4 grid of headline TTM metrics. */
function KeyMetricsGrid({ ttm }: { readonly ttm: FundamentalsTtm | null }) {
  return (
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
      <MetricCell label="Market Cap" value={formatCurrency(ttm?.marketCap ?? null)} />
      <MetricCell label="P/E Ratio" value={formatRatio(ttm?.peRatio ?? null)} />
      <MetricCell label="EPS (TTM)" value={formatEps(ttm?.epsDiluted ?? null)} />
      <MetricCell label="Revenue" value={formatCurrency(ttm?.revenue ?? null)} />
      <MetricCell label="Gross Margin" value={formatPercent(ttm?.grossMargin ?? null)} />
      <MetricCell label="Op. Margin" value={formatPercent(ttm?.operatingMargin ?? null)} />
      <MetricCell label="Net Margin" value={formatPercent(ttm?.netMargin ?? null)} />
      <MetricCell label="Div. Yield" value={formatPercent(ttm?.dividendYield ?? null)} />
    </div>
  );
}

/** Colored growth percentage cell for the quarterly table. */
function GrowthCell({ value }: { readonly value: number | null }) {
  if (!isDisplayable(value)) {
    return <span className="text-text-muted">--</span>;
  }

  const pct = (value * 100).toFixed(2);
  let colorClass = 'text-text-muted';
  if (value > 0) colorClass = 'text-accent-green';
  else if (value < 0) colorClass = 'text-accent-red';

  return <span className={colorClass}>{pct}%</span>;
}

/** Table showing up to 4 most recent quarterly filings. */
function QuarterlyTable({ quarters }: { readonly quarters: FundamentalsQuarter[] }) {
  if (quarters.length === 0) return null;

  return (
    <table className="w-full text-xs font-mono">
      <thead>
        <tr className="text-text-muted border-b border-terminal-border">
          <th className="text-left py-1 pr-2 font-normal">Period</th>
          <th className="text-left py-1 pr-2 font-normal">Filing Date</th>
          <th className="text-right py-1 pr-2 font-normal">EPS</th>
          <th className="text-right py-1 pr-2 font-normal">Rev. Growth</th>
          <th className="text-right py-1 font-normal">EPS Growth</th>
        </tr>
      </thead>
      <tbody>
        {quarters.slice(0, 4).map((q) => (
          <tr key={q.period} className="border-b border-terminal-border/30">
            <td className="text-text-primary py-1 pr-2">{q.period}</td>
            <td className="text-text-muted py-1 pr-2">{q.filingDate ?? '--'}</td>
            <td className="text-text-primary text-right py-1 pr-2">
              {formatEps(q.epsDiluted)}
            </td>
            <td className="text-right py-1 pr-2">
              <GrowthCell value={q.revenueGrowthYoy} />
            </td>
            <td className="text-right py-1">
              <GrowthCell value={q.epsGrowthYoy} />
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

/** Single horizontal key-value row for ratios. */
function KeyRatioRow({
  label,
  value,
}: {
  readonly label: string;
  readonly value: string;
}) {
  return (
    <div className="flex justify-between py-0.5">
      <span className="text-text-muted text-xs">{label}</span>
      <span className="text-text-primary font-mono text-xs">{value}</span>
    </div>
  );
}

/** List of 3 key financial ratios. */
function KeyRatiosList({ ttm }: { readonly ttm: FundamentalsTtm | null }) {
  return (
    <div>
      <KeyRatioRow label="Debt/Equity" value={formatRatio(ttm?.debtToEquity ?? null)} />
      <KeyRatioRow label="ROE" value={formatPercent(ttm?.returnOnEquity ?? null)} />
      <KeyRatioRow label="FCF" value={formatCurrency(ttm?.freeCashFlow ?? null)} />
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

/** Fundamentals panel for the active ticker. */
export default function Fundamentals({ symbol }: { symbol: string }) {
  const { data, loading, error } = useFundamentals(symbol);

  return (
    <div className="bg-terminal-panel border border-terminal-border rounded p-4 h-full flex flex-col overflow-hidden">
      <h3 className="text-text-primary font-mono text-sm mb-2">
        Fundamentals{symbol ? ' \u2014 ' + symbol : ''}
      </h3>

      <div className="flex-1 overflow-y-auto space-y-3">
        {loading ? (
          <LoadingSkeleton />
        ) : error ? (
          <ErrorState message={error} />
        ) : !data ? (
          <EmptyState />
        ) : (
          <>
            <KeyMetricsGrid ttm={data.ttm} />
            <QuarterlyTable quarters={data.quarterly} />
            <KeyRatiosList ttm={data.ttm} />
            {data.dataSources && (
              <div className="text-text-muted text-xs pt-1 border-t border-terminal-border/30">
                Data: {data.dataSources.financials}, {data.dataSources.marketData}
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
