/**
 * Macro Calendar panel displaying upcoming and recent economic events,
 * importance filtering, surprise indicators, and event-type reaction heatmap.
 * All sub-components are file-private (not exported).
 * @generated by code-generator (Agent #19)
 */
import React, { useState, useMemo } from 'react';
import { useMacroCalendar, useMacroReaction } from '../hooks/useMacroCalendar';
import type {
  MacroCalendarEvent, MacroReactionData, MacroReactionAverages,
  ImportanceLevel, SurpriseDirection, MacroEventType,
} from '../types/macro';
import {
  IMPORTANCE_CONFIG, EVENT_TYPE_DISPLAY_NAMES, VALID_EVENT_TYPES,
  formatEventValue, formatSurprise,
} from '../types/macro';

interface MacroCalendarProps {
  readonly symbol: string;
}

/** Pulsing skeleton placeholder shown while calendar data loads. */
function LoadingSkeleton() {
  return (
    <div className="flex flex-col gap-2 p-3 bg-terminal-bg font-mono text-sm">
      {[0, 1, 2, 3, 4].map((i) => (
        <div key={i} className="h-8 animate-pulse bg-terminal-panel rounded" />
      ))}
    </div>
  );
}

/** Static error message in red. Never reflects user input (XSS prevention). */
function ErrorState({ error }: { readonly error: string }) {
  return (
    <div className="p-3 bg-terminal-bg font-mono text-sm">
      <p className="text-accent-red text-sm">{error}</p>
    </div>
  );
}

/** Muted text shown when no calendar events are available. */
function EmptyState() {
  return (
    <div className="p-3 bg-terminal-bg font-mono text-sm">
      <p className="text-text-muted text-xs">No upcoming economic events found</p>
    </div>
  );
}

/** Four-button filter bar: All, High, Med, Low. */
const ImportanceFilter = React.memo(function ImportanceFilter({
  active, onChange, counts,
}: {
  readonly active: ImportanceLevel | 'all';
  readonly onChange: (level: ImportanceLevel | 'all') => void;
  readonly counts: { high: number; medium: number; low: number };
}) {
  const total = counts.high + counts.medium + counts.low;
  const buttons: Array<{ value: ImportanceLevel | 'all'; label: string; count: number }> = [
    { value: 'all', label: 'All', count: total },
    { value: 'high', label: 'High', count: counts.high },
    { value: 'medium', label: 'Med', count: counts.medium },
    { value: 'low', label: 'Low', count: counts.low },
  ];
  return (
    <div className="flex gap-1">
      {buttons.map((btn) => (
        <button
          key={btn.value}
          type="button"
          onClick={() => onChange(btn.value)}
          className={`px-2 py-1 rounded text-xs font-mono transition-colors duration-100 ${
            active === btn.value
              ? 'bg-terminal-border text-text-primary'
              : 'text-text-muted hover:text-text-secondary'
          }`}
        >
          {btn.label} ({btn.count})
        </button>
      ))}
    </div>
  );
});

/** Compact badge showing the event type. */
function EventTypeBadge({ eventType }: { readonly eventType: MacroEventType | null }) {
  if (eventType === null) return <span className="text-text-muted text-xs">Other</span>;
  return (
    <span className="text-text-secondary text-xs font-bold">
      {EVENT_TYPE_DISPLAY_NAMES[eventType] ?? eventType}
    </span>
  );
}

/** Surprise direction indicator: above=green, below=red, inline=muted. */
function SurpriseIndicator({ direction, actual, expected }: {
  readonly direction: SurpriseDirection;
  readonly actual: number | null;
  readonly expected: number | null;
}) {
  if (actual === null || expected === null) {
    return <span className="text-text-muted text-xs">--</span>;
  }
  const delta = actual - expected;
  const colorClass = direction === 'above' ? 'text-accent-green'
    : direction === 'below' ? 'text-accent-red' : 'text-text-muted';
  return <span className={`text-xs ${colorClass}`}>{formatSurprise(direction, delta)}</span>;
}

/** Compact badge showing importance level with color. */
function ImportanceBadge({ level }: { readonly level: ImportanceLevel }) {
  const config = IMPORTANCE_CONFIG[level] ?? IMPORTANCE_CONFIG.low;
  return <span className={`text-xs ${config.colorClass}`}>{config.label}</span>;
}

/** Single row in the events table. */
function EventRow({ event, isPast, isExpanded, onToggle, symbol }: {
  readonly event: MacroCalendarEvent;
  readonly isPast: boolean;
  readonly isExpanded: boolean;
  readonly onToggle: () => void;
  readonly symbol: string;
}) {
  const canExpand = event.eventType !== null && symbol !== '';
  const surpriseDir: SurpriseDirection =
    event.actual !== null && event.expected !== null
      ? event.actual > event.expected ? 'above'
        : event.actual < event.expected ? 'below' : 'inline'
      : 'inline';
  return (
    <tr className={`border-b border-terminal-border hover:bg-terminal-panel transition-colors duration-100 ${isPast ? 'opacity-50' : ''}`}>
      <td className="py-1 px-2 text-xs text-text-muted whitespace-nowrap">{event.date}</td>
      <td className="py-1 px-2">
        <div className="flex items-center gap-2">
          <EventTypeBadge eventType={event.eventType} />
          {canExpand && (
            <button type="button" onClick={onToggle}
              className="text-text-muted hover:text-text-primary text-xs"
              aria-label={isExpanded ? 'Collapse reaction data' : 'Expand reaction data'}>
              {isExpanded ? '\u25BC' : '\u25B6'}
            </button>
          )}
        </div>
      </td>
      <td className="py-1 px-2 text-xs text-text-primary whitespace-nowrap">
        {formatEventValue(event.actual, event.unit)}
      </td>
      <td className="py-1 px-2 text-xs text-text-muted whitespace-nowrap">
        {formatEventValue(event.expected, event.unit)}
      </td>
      <td className="py-1 px-2 text-xs text-text-muted whitespace-nowrap">
        {formatEventValue(event.previous, event.unit)}
      </td>
      <td className="py-1 px-2">
        <SurpriseIndicator direction={surpriseDir} actual={event.actual} expected={event.expected} />
      </td>
      <td className="py-1 px-2"><ImportanceBadge level={event.importance} /></td>
    </tr>
  );
}

/** Single cell in the reaction heatmap, color-coded by return value. */
function HeatmapCell({ value, label }: { readonly value: number | null; readonly label: string }) {
  const colorClass = value === null ? 'text-text-muted'
    : value > 0 ? 'text-accent-green' : value < 0 ? 'text-accent-red' : 'text-text-muted';
  return (
    <div className="flex flex-col items-center p-1">
      <span className="text-text-muted text-xs">{label}</span>
      <span className={`text-xs font-bold ${colorClass}`}>
        {value === null ? '--' : `${value > 0 ? '+' : ''}${value.toFixed(2)}%`}
      </span>
    </div>
  );
}

/** Displays reaction averages for beat/miss scenarios. */
function ReactionAverages({ averages }: { readonly averages: MacroReactionAverages }) {
  return (
    <div className="grid grid-cols-5 gap-1 bg-terminal-panel rounded p-2">
      <HeatmapCell value={averages.avgReturn1dOnBeat} label="1D Beat" />
      <HeatmapCell value={averages.avgReturn1dOnMiss} label="1D Miss" />
      <HeatmapCell value={averages.avgReturn5dOnBeat} label="5D Beat" />
      <HeatmapCell value={averages.avgReturn5dOnMiss} label="5D Miss" />
      <div className="flex flex-col items-center p-1">
        <span className="text-text-muted text-xs">Vol Ratio</span>
        <span className="text-text-primary text-xs font-bold">
          {averages.avgVolumeRatio !== null ? `${averages.avgVolumeRatio.toFixed(1)}x` : '--'}
        </span>
      </div>
    </div>
  );
}

/** Expandable heatmap panel showing historical price reactions. */
const HeatmapPanel = React.memo(function HeatmapPanel({ reactionData, loading, error }: {
  readonly reactionData: MacroReactionData | null;
  readonly loading: boolean;
  readonly error: string | null;
}) {
  if (loading) {
    return (
      <tr><td colSpan={7} className="py-2 px-4">
        <div className="h-12 animate-pulse bg-terminal-panel rounded" />
      </td></tr>
    );
  }
  if (error) {
    return (
      <tr><td colSpan={7} className="py-2 px-4">
        <p className="text-accent-red text-xs">{error}</p>
      </td></tr>
    );
  }
  if (!reactionData || reactionData.reactions.length === 0) {
    return (
      <tr><td colSpan={7} className="py-2 px-4">
        <p className="text-text-muted text-xs">No historical reaction data available</p>
      </td></tr>
    );
  }
  return (
    <tr><td colSpan={7} className="py-2 px-4">
      <div className="flex flex-col gap-2">
        <div className="text-text-muted text-xs">
          Historical reactions ({reactionData.sampleSize} events)
        </div>
        <ReactionAverages averages={reactionData.averages} />
      </div>
    </td></tr>
  );
});

/** Main events table with filterable rows and expandable reaction panels. */
const EventsTable = React.memo(function EventsTable({
  events, symbol, expandedEventType, onToggleExpand,
  reactionData, reactionLoading, reactionError,
}: {
  readonly events: MacroCalendarEvent[];
  readonly symbol: string;
  readonly expandedEventType: string | null;
  readonly onToggleExpand: (eventType: string) => void;
  readonly reactionData: MacroReactionData | null;
  readonly reactionLoading: boolean;
  readonly reactionError: string | null;
}) {
  const today = new Date().toISOString().slice(0, 10);
  const thClass = 'py-1 px-2 text-xs text-text-muted font-normal';
  return (
    <div className="overflow-x-auto">
      <table className="w-full text-left">
        <thead>
          <tr className="border-b border-terminal-border">
            <th className={thClass}>Date</th>
            <th className={thClass}>Event</th>
            <th className={thClass}>Actual</th>
            <th className={thClass}>Expected</th>
            <th className={thClass}>Previous</th>
            <th className={thClass}>Surprise</th>
            <th className={thClass}>Impact</th>
          </tr>
        </thead>
        <tbody>
          {events.map((event, idx) => {
            const isPast = event.date !== '' && event.date < today;
            const eventKey = event.eventType ?? `other-${idx}`;
            const isExpanded = expandedEventType !== null
              && event.eventType !== null
              && expandedEventType === event.eventType;
            return (
              <React.Fragment key={`${event.date}-${eventKey}-${idx}`}>
                <EventRow
                  event={event} isPast={isPast} isExpanded={isExpanded}
                  onToggle={() => { if (event.eventType !== null) onToggleExpand(event.eventType); }}
                  symbol={symbol}
                />
                {isExpanded && (
                  <HeatmapPanel
                    reactionData={reactionData} loading={reactionLoading} error={reactionError}
                  />
                )}
              </React.Fragment>
            );
          })}
        </tbody>
      </table>
    </div>
  );
});

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export default function MacroCalendar({ symbol }: MacroCalendarProps) {
  const { data, loading, error } = useMacroCalendar();
  const {
    data: reactionData, loading: reactionLoading,
    error: reactionError, fetchReaction,
  } = useMacroReaction();

  const [importanceFilter, setImportanceFilter] = useState<ImportanceLevel | 'all'>('all');
  const [expandedEventType, setExpandedEventType] = useState<string | null>(null);

  const filteredEvents = useMemo(() => {
    if (!data) return [];
    let events = data.events;
    if (importanceFilter !== 'all') {
      events = events.filter((e) => e.importance === importanceFilter);
    }
    const today = new Date().toISOString().slice(0, 10);
    const future = events.filter((e) => e.date >= today);
    const past = events.filter((e) => e.date < today);
    future.sort((a, b) => a.date.localeCompare(b.date));
    past.sort((a, b) => b.date.localeCompare(a.date));
    return [...future, ...past];
  }, [data, importanceFilter]);

  const importanceCounts = useMemo(() => {
    if (!data) return { high: 0, medium: 0, low: 0 };
    return {
      high: data.events.filter((e) => e.importance === 'high').length,
      medium: data.events.filter((e) => e.importance === 'medium').length,
      low: data.events.filter((e) => e.importance === 'low').length,
    };
  }, [data]);

  const handleToggleExpand = (eventType: string) => {
    if (expandedEventType === eventType) {
      setExpandedEventType(null);
    } else {
      setExpandedEventType(eventType);
      if (symbol && VALID_EVENT_TYPES.has(eventType)) {
        fetchReaction(symbol, eventType);
      }
    }
  };

  return (
    <div className="bg-terminal-panel border border-terminal-border rounded p-4 h-full flex flex-col">
      <h3 className="text-text-primary font-mono text-sm mb-2">Macro Calendar</h3>
      {loading && <LoadingSkeleton />}
      {!loading && error && <ErrorState error={error} />}
      {!loading && !error && (!data || filteredEvents.length === 0) && <EmptyState />}
      {!loading && !error && data && filteredEvents.length > 0 && (
        <div className="flex flex-col gap-2 flex-1 min-h-0">
          <ImportanceFilter
            active={importanceFilter} onChange={setImportanceFilter} counts={importanceCounts}
          />
          <div className="flex-1 overflow-auto">
            <EventsTable
              events={filteredEvents} symbol={symbol}
              expandedEventType={expandedEventType} onToggleExpand={handleToggleExpand}
              reactionData={reactionData} reactionLoading={reactionLoading}
              reactionError={reactionError}
            />
          </div>
        </div>
      )}
    </div>
  );
}
