/**
 * News feed panel displaying per-ticker news articles with sentiment badges.
 * Supports pagination via "Load More" button and live-updating relative timestamps.
 * @generated by unit-implementer (Agent #21)
 */
import { useEffect, useReducer, useState } from 'react';
import type { NewsArticle, SentimentDirection } from '../types/news';
import { formatRelativeTime, RELATIVE_TIME_UPDATE_INTERVAL_MS } from '../types/news';
import { useNewsFeed } from '../hooks/useNewsFeed';
import { useWebSocketContext } from '../contexts/WebSocketContext';
import { WS_CHANNELS } from '../types/websocket';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface NewsFeedProps {
  readonly symbol: string;
}

// ---------------------------------------------------------------------------
// Sentiment badge helpers
// ---------------------------------------------------------------------------

interface SentimentStyle {
  readonly bgClass: string;
  readonly label: string;
}

function getSentimentStyle(sentiment: SentimentDirection): SentimentStyle {
  switch (sentiment) {
    case 'bullish':
      return { bgClass: 'bg-accent-green', label: 'Bullish' };
    case 'bearish':
      return { bgClass: 'bg-accent-red', label: 'Bearish' };
    case 'neutral':
    default:
      return { bgClass: 'bg-gray-600', label: 'Neutral' };
  }
}

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

/** Animated loading skeleton with placeholder article cards. */
function LoadingSkeleton() {
  return (
    <div className="space-y-3">
      {[0, 1, 2].map((i) => (
        <div
          key={i}
          className="animate-pulse border border-terminal-border rounded p-3 space-y-2"
        >
          <div className="h-3 bg-terminal-border rounded w-3/4" />
          <div className="h-2 bg-terminal-border rounded w-1/2" />
          <div className="flex gap-2">
            <div className="h-2 bg-terminal-border rounded w-16" />
            <div className="h-4 bg-terminal-border rounded w-20" />
          </div>
        </div>
      ))}
    </div>
  );
}

/** Error state display with optional retry indicator. */
function ErrorState({ message }: { readonly message: string }) {
  const isRetrying = message.includes('Retrying');

  return (
    <div className="flex-1 flex items-center justify-center flex-col gap-2">
      <p className="text-accent-red font-mono text-xs">{message}</p>
      {isRetrying && (
        <div className="flex items-center gap-1.5">
          <div className="h-2 w-2 rounded-full bg-accent-amber animate-pulse" />
          <span className="text-text-secondary font-mono text-xs">
            Retrying...
          </span>
        </div>
      )}
    </div>
  );
}

/** Empty state display showing symbol-specific message. */
function EmptyState({ symbol }: { readonly symbol: string }) {
  return (
    <div className="flex-1 flex items-center justify-center">
      <p className="text-text-secondary font-mono text-xs">
        No news articles found for {symbol}
      </p>
    </div>
  );
}

/** Sentiment badge showing direction label and confidence score. */
function SentimentBadge({
  sentiment,
  score,
}: {
  readonly sentiment: SentimentDirection;
  readonly score: number;
}) {
  const style = getSentimentStyle(sentiment);

  return (
    <span
      className={`${style.bgClass} text-white font-mono text-xs px-1.5 py-0.5 rounded whitespace-nowrap`}
    >
      {style.label} {score.toFixed(2)}
    </span>
  );
}

/** Individual article card with headline link, source, timestamp, and sentiment. */
function ArticleCard({ article }: { readonly article: NewsArticle }) {
  const absoluteTime = article.publishedAt.toLocaleString();

  return (
    <div className="border border-terminal-border rounded p-3 space-y-1.5">
      {/* Headline */}
      {article.url ? (
        <a
          href={article.url}
          target="_blank"
          rel="noopener noreferrer"
          className="text-text-primary font-mono text-xs font-bold hover:text-amber-400 transition-colors duration-100 block leading-snug"
        >
          {article.headline}
        </a>
      ) : (
        <span className="text-text-primary font-mono text-xs font-bold block leading-snug">
          {article.headline}
        </span>
      )}

      {/* Source + timestamp row */}
      <div className="flex items-center gap-2 flex-wrap">
        <span className="text-text-secondary font-mono text-xs">
          {article.source}
        </span>
        <span
          className="text-text-secondary font-mono text-xs"
          title={absoluteTime}
        >
          {formatRelativeTime(article.publishedAt)}
        </span>
      </div>

      {/* Sentiment badge */}
      <div>
        <SentimentBadge
          sentiment={article.sentiment}
          score={article.sentimentScore}
        />
      </div>
    </div>
  );
}

/** "Load More" button for pagination. */
function LoadMoreButton({
  onClick,
  loading,
}: {
  readonly onClick: () => void;
  readonly loading: boolean;
}) {
  return (
    <div className="pt-2 shrink-0">
      <button
        type="button"
        onClick={onClick}
        disabled={loading}
        className="
          w-full px-2 py-1.5 rounded text-xs font-mono font-bold
          bg-terminal-border text-text-primary
          hover:bg-amber-500 hover:text-terminal-bg
          disabled:opacity-40 disabled:cursor-not-allowed
          transition-colors duration-100
        "
      >
        {loading ? 'Loading...' : 'Load More'}
      </button>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

/** News feed panel -- fetches and displays news articles for the active ticker. */
export default function NewsFeed({ symbol }: NewsFeedProps) {
  const {
    articles,
    hasMore,
    loading,
    loadingMore,
    error,
    loadMore,
  } = useNewsFeed(symbol);

  const { subscribe, unsubscribe, onMessage } = useWebSocketContext();

  // Live articles received via WebSocket, displayed above REST-fetched articles.
  const [liveArticles, setLiveArticles] = useState<NewsArticle[]>([]);

  // Clear live articles when symbol changes.
  useEffect(() => {
    setLiveArticles([]);
  }, [symbol]);

  // Subscribe to news alerts and prepend live articles.
  useEffect(() => {
    if (!symbol) return;

    subscribe(WS_CHANNELS.NewsAlerts);

    const removeListener = onMessage('news_alert', (msg) => {
      if (msg.symbol !== symbol) return;

      const article: NewsArticle = {
        id: `ws-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        headline: msg.headline,
        summary: '',
        source: 'Live',
        url: null,
        imageUrl: null,
        publishedAt: new Date(msg.timestamp),
        category: null,
        relatedTickers: [msg.symbol],
        sentiment: msg.sentiment.label as SentimentDirection,
        sentimentScore: msg.sentiment.score,
      };

      setLiveArticles((prev) => [article, ...prev].slice(0, 50));
    });

    return () => {
      removeListener();
      unsubscribe(WS_CHANNELS.NewsAlerts);
    };
  }, [symbol, subscribe, unsubscribe, onMessage]);

  // Merge live + REST articles for rendering.
  const allArticles = [...liveArticles, ...articles];

  // Force re-render every minute to keep relative timestamps fresh.
  const [, forceUpdate] = useReducer((c: number) => c + 1, 0);

  useEffect(() => {
    if (allArticles.length === 0) return;

    const interval = setInterval(forceUpdate, RELATIVE_TIME_UPDATE_INTERVAL_MS);
    return () => clearInterval(interval);
  }, [allArticles.length]);

  return (
    <div className="bg-terminal-panel border border-terminal-border rounded p-4 h-full flex flex-col overflow-hidden">
      {/* Header */}
      <h3 className="text-text-primary font-mono text-sm mb-2">
        News {symbol ? `\u2014 ${symbol}` : ''}
      </h3>

      {/* Loading state */}
      {loading && <LoadingSkeleton />}

      {/* Error state */}
      {error && !loading && <ErrorState message={error} />}

      {/* Empty state */}
      {!loading && !error && allArticles.length === 0 && <EmptyState symbol={symbol} />}

      {/* Article list */}
      {!loading && allArticles.length > 0 && (
        <div className="flex-1 overflow-auto space-y-2 min-h-0">
          {allArticles.map((article) => (
            <ArticleCard key={article.id} article={article} />
          ))}
        </div>
      )}

      {/* Load More */}
      {!loading && hasMore && (
        <LoadMoreButton onClick={loadMore} loading={loadingMore} />
      )}
    </div>
  );
}
