/**
 * Watchlist panel component with add/remove functionality.
 * Self-contained: uses useWatchlist() hook and useTickerContext() internally.
 * @generated by code-generator (Agent #19)
 */
import { useState, useEffect, useReducer, useRef } from 'react';
import type { FormEvent } from 'react';
import type { WatchlistEntry } from '../types/watchlist';
import { SYMBOL_REGEX } from '../types/watchlist';
import { useWatchlist } from '../hooks/useWatchlist';
import { useTickerContext } from '../contexts/TickerContext';
import { useWebSocketContext } from '../contexts/WebSocketContext';
import { WS_CHANNELS } from '../types/websocket';

/**
 * Format a percentage value for display.
 * Positive values are green with "+" prefix, negative are red, zero/null is gray.
 */
function formatPercent(value: number | null): { text: string; colorClass: string } {
  if (value === null) {
    return { text: '\u2014', colorClass: 'text-text-secondary' };
  }
  if (value > 0) {
    return { text: `+${value.toFixed(2)}%`, colorClass: 'text-green-400' };
  }
  if (value < 0) {
    return { text: `${value.toFixed(2)}%`, colorClass: 'text-red-400' };
  }
  return { text: '0.00%', colorClass: 'text-text-secondary' };
}

/**
 * Map a composite signal direction string to a Tailwind text colour class.
 */
function getSignalColor(signal: string | null): string {
  if (signal === null) return 'text-text-secondary';
  switch (signal) {
    case 'strong_bullish':
    case 'bullish':
      return 'text-green-400';
    case 'strong_bearish':
    case 'bearish':
      return 'text-red-400';
    case 'neutral':
    default:
      return 'text-text-secondary';
  }
}

/** Price override from WebSocket. */
interface PriceOverride {
  readonly price: number;
  readonly changePercent: number;
}

/** Props for the internal WatchlistRow sub-component. */
interface WatchlistRowProps {
  readonly entry: WatchlistEntry;
  readonly isSelected: boolean;
  readonly onSelect: (symbol: string) => void;
  readonly onRemove: (symbol: string) => void;
  readonly priceOverride?: PriceOverride;
}

/** A single row in the watchlist table. */
function WatchlistRow({ entry, isSelected, onSelect, onRemove, priceOverride }: WatchlistRowProps) {
  const displayPrice = priceOverride?.price ?? entry.last_price;
  const displayChangePercent = priceOverride?.changePercent ?? entry.price_change_percent;
  const pct = formatPercent(displayChangePercent);
  const signalColor = getSignalColor(entry.last_composite_signal);

  return (
    <li
      className={`
        flex items-center justify-between px-2 py-1 rounded cursor-pointer
        hover:bg-terminal-border transition-colors duration-100
        ${isSelected ? 'border-l-2 border-amber-500 pl-1.5' : ''}
      `}
      onClick={() => onSelect(entry.symbol)}
      onKeyDown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          onSelect(entry.symbol);
        }
      }}
      role="button"
      tabIndex={0}
    >
      <div className="flex items-center gap-2 min-w-0">
        <span className="text-text-primary font-mono text-xs font-bold whitespace-nowrap">
          {entry.symbol}
        </span>
        <span className="text-text-secondary font-mono text-xs whitespace-nowrap">
          {displayPrice !== null ? displayPrice.toFixed(2) : '\u2014'}
        </span>
        <span className={`font-mono text-xs whitespace-nowrap ${pct.colorClass}`}>
          {pct.text}
        </span>
      </div>

      <div className="flex items-center gap-2 shrink-0">
        {entry.last_composite_signal !== null && (
          <span className={`font-mono text-xs ${signalColor}`}>
            {entry.last_composite_signal}
            {entry.last_composite_confidence !== null && (
              <span className="text-text-secondary ml-1">
                {(entry.last_composite_confidence * 100).toFixed(0)}%
              </span>
            )}
          </span>
        )}
        <button
          type="button"
          onClick={(e) => {
            e.stopPropagation();
            onRemove(entry.symbol);
          }}
          className="text-text-secondary hover:text-red-400 font-mono text-xs px-1 transition-colors duration-100"
          aria-label="Remove ticker"
        >
          &times;
        </button>
      </div>
    </li>
  );
}

/** Watchlist panel with add form, entry list, and remove controls. */
export default function Watchlist() {
  const { activeTicker, setActiveTicker } = useTickerContext();
  const {
    entries,
    count,
    maxAllowed,
    loading,
    error,
    adding,
    addEntry,
    removeEntry,
  } = useWatchlist();

  const { subscribe, unsubscribe, onMessage } = useWebSocketContext();

  // Price overrides from WebSocket -- stored in a ref to avoid re-render storms,
  // with a manual forceRender dispatch to batch updates.
  const priceOverridesRef = useRef<Map<string, PriceOverride>>(new Map());
  const [, forceRender] = useReducer((x: number) => x + 1, 0);

  // RAF coalescing: multiple price updates within a single animation frame
  // (~16ms) collapse into one render instead of one render per message.
  const rafIdRef = useRef<number | null>(null);

  useEffect(() => {
    subscribe(WS_CHANNELS.PriceUpdates);

    const removeListener = onMessage('price_update', (msg) => {
      priceOverridesRef.current.set(msg.symbol, {
        price: msg.price,
        changePercent: msg.change_percent,
      });
      if (rafIdRef.current === null) {
        rafIdRef.current = requestAnimationFrame(() => {
          rafIdRef.current = null;
          forceRender();
        });
      }
    });

    return () => {
      removeListener();
      if (rafIdRef.current !== null) {
        cancelAnimationFrame(rafIdRef.current);
        rafIdRef.current = null;
      }
      unsubscribe(WS_CHANNELS.PriceUpdates);
    };
  }, [subscribe, unsubscribe, onMessage]);

  // Clean stale price overrides when the watchlist entries change.
  // This prevents the Map from growing unboundedly when tickers are removed.
  useEffect(() => {
    const activeSymbols = new Set(entries.map((e) => e.symbol));
    for (const key of priceOverridesRef.current.keys()) {
      if (!activeSymbols.has(key)) {
        priceOverridesRef.current.delete(key);
      }
    }
  }, [entries]);

  const [inputValue, setInputValue] = useState('');

  function handleInputChange(e: React.ChangeEvent<HTMLInputElement>): void {
    setInputValue(e.target.value.toUpperCase());
  }

  async function handleSubmit(e: FormEvent): Promise<void> {
    e.preventDefault();
    const trimmed = inputValue.trim();
    if (!SYMBOL_REGEX.test(trimmed)) return;
    await addEntry(trimmed);
    setInputValue('');
  }

  function handleSelect(symbol: string): void {
    setActiveTicker(symbol);
  }

  return (
    <div className="bg-terminal-panel border border-terminal-border rounded p-4 h-full flex flex-col overflow-hidden">
      {/* Header */}
      <h3 className="text-text-primary font-mono text-sm mb-2">Watchlist</h3>

      {/* Add form */}
      <form onSubmit={handleSubmit} className="flex gap-1 mb-2">
        <input
          type="text"
          value={inputValue}
          onChange={handleInputChange}
          placeholder="AAPL"
          maxLength={5}
          className="
            flex-1 min-w-0 px-2 py-1 rounded text-xs font-mono
            bg-terminal-bg border border-terminal-border
            text-text-primary placeholder-text-secondary
            focus:outline-none focus:border-amber-500
          "
          disabled={adding}
        />
        <button
          type="submit"
          disabled={adding || !SYMBOL_REGEX.test(inputValue.trim())}
          className="
            px-2 py-1 rounded text-xs font-mono font-bold
            bg-amber-500 text-terminal-bg
            hover:bg-amber-400 disabled:opacity-40 disabled:cursor-not-allowed
            transition-colors duration-100
          "
        >
          +
        </button>
      </form>

      {/* Count display */}
      <div className="text-text-secondary font-mono text-xs mb-2">
        {count} / {maxAllowed}
      </div>

      {/* Error display */}
      {error && (
        <p className="text-red-400 font-mono text-xs mb-2">{error}</p>
      )}

      {/* Loading state */}
      {loading && (
        <div className="flex-1 flex items-center justify-center">
          <span className="text-text-secondary font-mono text-xs animate-pulse">
            Loading watchlist...
          </span>
        </div>
      )}

      {/* Empty state */}
      {!loading && !error && entries.length === 0 && (
        <div className="flex-1 flex items-center justify-center">
          <p className="text-text-secondary font-mono text-xs">
            Watchlist is empty. Add a ticker above.
          </p>
        </div>
      )}

      {/* Entry list */}
      {!loading && entries.length > 0 && (
        <ul className="flex-1 overflow-auto space-y-0.5">
          {entries.map((entry) => (
            <WatchlistRow
              key={entry.symbol}
              entry={entry}
              isSelected={entry.symbol === activeTicker}
              onSelect={handleSelect}
              onRemove={removeEntry}
              priceOverride={priceOverridesRef.current.get(entry.symbol)}
            />
          ))}
        </ul>
      )}
    </div>
  );
}
